# <font color = darkblue> Bem-vindo/a!
##### Iremos guiá-lo por este notebook relativo a uma data analysis sobre dados de pacientes de carcinoma hepatocelular.

### Índice:

    1. Introdução à análise:
        1.1 Contexto do problema
        1.2 Expectativas e objetivos
        
    2. Inicialização do dataset
    
    3. Estatísticas descritivas báscias:
        3.1 Média
        3.2 Mediana
        3.3 Desvio
        3.4 Assimetria
        3.5 Curtose
        
    4. Relotório de Análise - DataPrep
    
    5. Inputação dos missing values:
        5.1 Identificação visual dos missing values
        5.2 Heterogeneous Euclidean-Overlap Metric para medir distâncias entre pacientes
        5.3 Inputação de missing values por HEOM
    
    6. Ajuste de Outliers
        6.1 Identificação visual dos outliers
        6.2 K Nearest Neighbours para enquadramento dos ouliers 
        6.2 Expansão visual dos outliers

# <font color = darkblue> 2. Inicialização do dataset

In [2]:
import pandas as pd
import numpy as np
import heapq
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
class Dataset:
    def __init__(self, df, missing_values):
        self.df = df
        self.missing_values = missing_values


    def pintarMissingValues(self):#pintar a tabela de missing values
        if self.missing_values is not None:#se existirem missing values
            self.df.replace(self.missing_values, "NaN", inplace=True)#substituir missing values por string "NaN" devido a limitação do site 
            return self.df.style.applymap(lambda valor: "color: red;" if valor=="NaN" else "")#pintar missing values a vermelho
        else: return self.df #se não existirem missing values


    def missing_values_percentagem(self):#Percentagem de missing values
        self.df.replace(self.missing_values, np.nan, inplace=True)#substituir missing values por NaN e nao string "NaN"
        missing_values_percentages = self.df.isnull().mean() * 100#calcular a percentagem de missing values
        return missing_values_percentages.tolist()#retornar a percentagem de missing values
    
    
    def remove_int_columns(self):
        df_copy = self.df.copy()  # create a copy of the dataframe
        numerical=self.df_num()
        common_columns = set(self.df.columns) & set(numerical.columns)
        df_copy = df_copy.drop(common_columns, axis=1)
        
        return df_copy
    

    def df_num(self):
        # Replace missing values with None
        dataframe= self.replace_nan_with_none()

        # Convert all columns to numeric, replacing non-numeric values with NaN
        for col in dataframe.columns:
            dataframe[col] = pd.to_numeric(dataframe[col], errors='coerce')

        # Remove columns that only contain None values
        self.df = dataframe.dropna(axis=1, how='all')

        return self.df


    def replace_nan_with_none(self):
        self.df.replace(self.missing_values, None, inplace=True)
        return self.df


    def pintarOutliers(self, df, outliers):
        def highlight_value(series, column):#Pintar as células que são outliers de azul
            return ['background-color: blue' if (column, index) in outliers else '' for index in series.index]
        return df.style.apply(lambda x: highlight_value(x, x.name), axis=0)#Aplicar a função a cada coluna
    

    def tabelaHEOM(self):
        self.df = self.replace_nan_with_none()#Trocar missing values para none
        tabela = pd.DataFrame()
        for i in range(len(self.df)):
            lista = []
            for j in range(len(self.df)):#Não interessa comparar pares de pacientes duas vezes
                if i >= j:
                    lista.append("X")# colocar x por motivos estéticos
                else:
                    lista.append(self.HEOM(i, j))# lista de um paciente em calculo HEOM

            tabela = pd.concat([tabela, pd.DataFrame({i: lista})], axis=1)#adicionar a lista à tabela
        return tabela
    

    def HEOM(self, paciente_1, paciente_2): #Heterogeneous Euclidean-Overlap Metric
        soma = 0
        for feature in self.df.columns:# iterar sobre as V
            distancia = self.distanciaGeral(feature, paciente_1, paciente_2)# calcular a sua "distancia"
            soma += distancia**2
        soma= soma**(1/2)
        return soma
    

    def distanciaGeral(self, feature:str, paciente_1:int, paciente_2:int)->int:
        try :#Se a variavel for numerica vem para aqui
            #distancia normalizada
            valorPaciente_1 = float(self.df.loc[paciente_1, feature])
            valorPaciente_2 = float(self.df.loc[paciente_2, feature])
            numeric_feature = pd.to_numeric(self.df[feature], errors='coerce')
            return abs(valorPaciente_1 - valorPaciente_2) / (numeric_feature.max() - numeric_feature.min())# retornar a range 
        except :#Se a variavel for categorica vem para aqui
            valorPaciente_1 = self.df.loc[paciente_1, feature]
            valorPaciente_2 = self.df.loc[paciente_2, feature]
            if valorPaciente_1 == valorPaciente_2 and  not pd.isna(valorPaciente_1):#Se forem iguais e não forem missing values
                return 0
            else: 
                return 1
    

    def outliers(self,info:str,vizinhos=None)->pd.DataFrame:
        # Selecionar apenas as colunas numéricas
        categorical_features = self.remove_int_columns() 
        numeric_df = self.df_num()

        colunas_numericas = numeric_df.columns
        if info == 'style':
            outliers = set()
        for coluna in colunas_numericas:#calcular os outliers usando o IQR
            if info == 'tratamento':
                outliers = []
            q1 = numeric_df[coluna].quantile(0.25)
            q3 = numeric_df[coluna].quantile(0.75)
            iqr = q3 - q1
            limite_inferior = q1 - 1.5 * iqr
            limite_superior = q3 + 1.5 * iqr
            for index, value in numeric_df[coluna].items():#adicionar outliers ao set
                if value < limite_inferior or value > limite_superior:
                    if info == 'tratamento' and coluna not in ["Iron", "Sat", "Ferritin"]:
                        if self.df.loc[index, coluna] > limite_superior * 5 or self.df.loc[index, coluna] < limite_inferior * 5:
                            outliers.append((index, coluna))
                    elif info == 'style':
                        outliers.add((coluna, index))
            if info == 'tratamento':
                self.df= self.tratamentoOutliers(outliers, coluna,vizinhos)
        if info == 'style':
            # Apply styling to outliers
            styled_df = self.pintarOutliers(numeric_df, outliers)
            return styled_df
        if info == 'tratamento': 
            self.df = (pd.concat([categorical_features,self.df ], axis=1))
            return self.df
    
    
    def tratamentoOutliers(self, outliers, coluna,vizinhos):
        
        lista_valores = self.df[coluna].tolist()#todos os valores da coluna 
        contador = -1
        valores_out = [self.df.loc[index,coluna] for index,coluna in outliers]#valores dos outliers
        for valor_outlier in valores_out:# iterar por todos os outliers
            contador+=1
            outlier = valor_outlier
            dicionario_distancias = []
            for valor in lista_valores:

                if outlier != valor and valor not in valores_out and not pd.isna(valor):

                    distancia = self.HEOM(lista_valores.index(valor), lista_valores.index(outlier))#calcular a distancia entre o outlier e os outros valores
                    if len(dicionario_distancias) < vizinhos:
                        heapq.heappush(dicionario_distancias, (-distancia, valor))
                    else:
                        if -distancia > dicionario_distancias[0][0]:
                            heapq.heapreplace(dicionario_distancias, (-distancia, valor))

            k_proximos = [abs(item[1]) for item in dicionario_distancias]# selecionar os k vizinhos mais proximos
            
            media = sum(k_proximos)/len(k_proximos)
            self.df.loc[outliers[contador][0], coluna] = media
        return self.df


    def fill_missing_values(self, nr_vizinhos:int) -> pd.DataFrame:

        self.df = self.replace_nan_with_none() # Replace missing values with None 

        self.df = self.df.drop(['Iron', 'Sat', 'Ferritin'], axis=1)# Drop unnecessary columns
        df_copiada = self.df.copy()# Create a copy of the DataFrame

        for i in range(len(self.df)): # Iterate over each row
            row = self.df.iloc[i]
            
            if row.isnull().any():# Check if the row has any missing values
                closest_rows = self.linhas_mais_proximas(nr_vizinhos, i)# Get the indices of the closest rows
    
                for col in self.df.columns:# Iterate over each column
                    if pd.isnull(row[col]): # If the value is missing, replace it with the most common value or mean from the closest rows
                        df_copiada.loc[i, col] = self.subs_na_tabela(closest_rows, col,nr_vizinhos,i)
        return df_copiada
    

    def subs_na_tabela(self, closest_rows:list, col:int,vizinhos,i)->float | str :
        # Initialize values
        column_values = []

        for row_index in closest_rows:
            try:
                # Check the type of values
                value = float(self.df.loc[row_index, col])
            except:
                value = self.df.loc[row_index, col]

            if value is not None and not pd.isna(value):
                column_values.append(value)
        if len(column_values) == 0:

            return self.subs_na_tabela(self.linhas_mais_proximas(vizinhos+1,i), col,vizinhos+1,i)
        # Calculate the result based on the type of values
        if isinstance(column_values[0], str):

            # If values are strings, return the most frequent value
            return max(set(column_values), key=column_values.count)
        elif isinstance(column_values[0], (int, float)):

            # If values are numeric, return the mean
            return np.mean(column_values)
        

    def linhas_mais_proximas(self, vizinhos:int,i:int)->list: # Calculate the HEOM distance for each other row
       
        heom_values = []

        for j in range(len(self.df)):

            if j != i:
                heom_distance = self.HEOM(i, j)# Calculate the HEOM distance
                if len(heom_values) < vizinhos: # If we have less than 'vizinhos' distances, we add it to the heap

                    heapq.heappush(heom_values, (-heom_distance, j))
                else:
                    if -heom_distance > heom_values[0][0]: # If the current distance is smaller than the largest distance in the heap, we replace it
                        heapq.heapreplace(heom_values, (-heom_distance, j))
    
        # Get the rows with the smallest HEOM distance
        closest_rows = [item[1] for item in heom_values]

        return closest_rows
    

    def categorical_to_numerical(self):
        """
        _summary_: converts all categorical features to numerical values

        _conversion_dictionary_:
            Male -> 0
            Female -> 1
            No -> 0
            Yes -> 1
            Disabled -> 0
            Ambulatory -> 1
            Restricted -> 2
            Selfcare -> 3
            Active -> 4
            None -> 0
            Grade I/II -> 1
            Grade III/IV -> 2
            Mild -> 1
            Moderate/Severe -> 2
            Dies -> 0
            Lives -> 1
            
        """
        words = ("Male","Female","No","Yes","Disabled","Ambulatory",
                 "Restricted","Selfcare","Active","None","Grade I/II",
                 "Grade III/IV","Mild","Moderate/Severe","Dies","Lives")
        values = (0,1,0,1,0,1,2,3,4,0,1,2,1,2,0,1)
        self.df.replace(words, values, inplace=True)
        return self.df

    def polirTabela(self):
        self.outilers


    @classmethod #este classmethod funciona como um construtor alternativo e construir um dataframe a partir de um arquivo cs

    def builderData(cls, df, missing_values): 
        try:
            if not isinstance(df, pd.DataFrame):# Handle DataFrame input directly
                df = pd.read_csv(df)
            df = df.copy()# Avoid modifying the original DataFrame
            return cls(df, missing_values)
        except (FileNotFoundError, pd.errors.ParserError):
            # Handle potential errors: file not found or parsing errors
            print(f"Erro: Não conseguiu ler a data de {df}.")
            raise

# <font color = darkblue> 3. Estatísticas descritivas básicas

### <font color = blue> 3.1. Média

In [177]:
data = Dataset.builderData("hcc_dataset.csv", "?")
data = data.df
data.to_csv("hcc_dataset.csv", index=False)
tabela = data.mean(numeric_only=True).to_frame("Média")
display(tabela)

                    Média
Age             64.690909
Grams_day       71.008547
Packs_year      20.464286
INR              1.421851
AFP          19299.951146
Hemoglobin      12.879012
MCV             95.119753
Leucocytes    1473.961549
Platelets   113206.442654
 Albumin         3.445535
Total_Bil        3.087938
ALT             67.093168
AST             96.382716
GGT            268.026543
ALP            212.211605
TP               8.961039
Creatinine       1.127089
Nodules          2.736196
Major_Dim        6.851172
Dir_Bil          1.930000
Iron            85.598837
Sat             37.028941
Ferritin       438.997647

### <font color = blue> 3.2. Mediana

In [176]:
data = Dataset.builderData("hcc_dataset.csv", "?")
data = data.df
data.to_csv("hcc_dataset.csv", index=False)
tabela = data.median(numeric_only=True).to_frame("Mediana")
display(tabela)

             Mediana
Age            66.00
Grams_day      75.00
Packs_year      0.00
INR             1.30
AFP            33.00
Hemoglobin     13.05
MCV            94.95
Leucocytes      7.20
Platelets   93000.00
 Albumin        3.40
Total_Bil       1.40
ALT            50.00
AST            71.00
GGT           179.50
ALP           162.00
TP              7.05
Creatinine      0.85
Nodules         2.00
Major_Dim       5.00
Dir_Bil         0.70
Iron           83.00
Sat            27.00
Ferritin      295.00

### <font color = blue> 3.3. Desvio Padrão

In [26]:
data = Dataset.builderData("hcc_dataset.csv", "?")
data = data.df
data.to_csv("hcc_dataset.csv", index=False)
tabela = data.std(numeric_only=True).to_frame("Desvio Padrão")
display(tabela)

            Desvio Padrão
Age             13.319534
Grams_day       76.277680
Packs_year      51.565130
INR              0.477816
AFP         149098.335581
Hemoglobin       2.145237
MCV              8.405846
Leucocytes    2909.106006
Platelets   107118.632481
 Albumin         0.685132
Total_Bil        5.499379
ALT             57.539747
AST             87.484241
GGT            258.750319
ALP            167.943548
TP              11.728739
Creatinine       0.955856
Nodules          1.797901
Major_Dim        5.095042
Dir_Bil          4.210452
Iron            55.698995
Sat             28.993552
Ferritin       457.114454

### <font color = blue> 3.4. Assimetria

In [28]:
data = Dataset.builderData("hcc_dataset.csv", "?")
data = data.df
data.to_csv("hcc_dataset.csv", index=False)
tabela = data.skew(numeric_only=True).to_frame("Assimetria")
display(tabela)

            Assimetria
Age          -0.779988
Grams_day     1.986666
Packs_year    7.886234
INR           3.587974
AFP          11.392308
Hemoglobin   -0.441710
MCV          -0.087315
Leucocytes    1.865177
Platelets     0.950930
 Albumin     -0.102843
Total_Bil     4.522439
ALT           2.619456
AST           2.721387
GGT           2.105514
ALP           2.317649
TP            6.111737
Creatinine    4.060195
Nodules       0.318755
Major_Dim     1.198030
Dir_Bil       4.616666
Iron          0.619699
Sat           0.952659
Ferritin      1.798995

### <font color = blue> 3.5. Curtose

In [178]:
data = Dataset.builderData("hcc_dataset.csv", "?")
data = data.df
data.to_csv("hcc_dataset.csv", index=False)
tabela = data.kurtosis(numeric_only=True).to_frame("Curtose")
display(tabela)

               Curtose
Age           0.846190
Grams_day     7.931784
Packs_year   74.241726
INR          18.965445
AFP         136.018560
Hemoglobin    0.402549
MCV           0.971063
Leucocytes    2.432640
Platelets     0.504059
 Albumin     -0.699851
Total_Bil    23.039993
ALT          10.128151
AST           8.889108
GGT           5.720737
ALP           6.522546
TP           38.986173
Creatinine   19.893154
Nodules      -1.707410
Major_Dim     0.541080
Dir_Bil      22.900901
Iron         -0.554939
Sat           0.134944
Ferritin      3.951051

# <font color = darkblue> 4. Relatório DataPrep

In [192]:
def criar_e_exibir_relatorio(ficheiro):
    data_file = pd.read_csv(ficheiro, na_values='?')
    data_file.to_csv(ficheiro, index=False)
    return create_report(data_file).show_browser()
criar_e_exibir_relatorio("hcc_dataset.csv")

  0%|          | 0/7332 [00:00<?, ?it/s]

C:\Users\diogo\anaconda3\Lib\site-packages\dask\core.py:127: RuntimeWarning: invalid value encountered in divide
  return func(*(_execute_task(a, cache) for a in args))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))
C:\Users\diogo\anaconda3\Lib\site-packages\dataprep\eda\distribution\render.py:274: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame({col: [nrows - npresent]}, index=["Others"]))

Este bloco de código destina-se à criação de um relatório com base na bibloteca ``dataprep``.
É expectável encontrar informações sobre:

* Percentagem de ``missing values``
* As mais ``importantes estatísticas descritivas`` de todas as variáveis
* Distribuições de dados em ``Q-Q Plot's`` e em ``BoxPlot's``
* ``Interações`` entre 2 variáveis
* ``Correlações`` entre variáveis
* entre outros

# <font color = darkblue> 5. Inputação dos missing values

### <font color = blue> 5.1. Identificação visual dos missing values

In [22]:
data = Dataset.builderData("hcc_dataset.csv", "?")
data.pintarMissingValues()

### <font color = blue> 5.2. Heterogeneous Euclidean-Overlap Metric

In [9]:
data = Dataset.builderData("hcc_dataset.csv", "?")
data.tabelaHEOM()

,0,1,2,3,4,5,6,7,8,9,...,155,156,157,158,159,160,161,162,163,164
0,X,X,X,X,X,X,X,X,X,X,...,X,X,X,X,X,X,X,X,X,X
1,5.299683,X,X,X,X,X,X,X,X,X,...,X,X,X,X,X,X,X,X,X,X
2,4.048287,5.915786,X,X,X,X,X,X,X,X,...,X,X,X,X,X,X,X,X,X,X
3,3.245281,5.343068,3.558409,X,X,X,X,X,X,X,...,X,X,X,X,X,X,X,X,X,X
4,3.683806,5.495465,2.698323,3.241517,X,X,X,X,X,X,...,X,X,X,X,X,X,X,X,X,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,4.379363,5.721385,4.636164,4.516116,4.314898,4.862136,4.360479,4.826378,4.910478,4.269307,...,5.068029,4.228015,4.727487,5.03952,5.009368,X,X,X,X,X
161,4.502504,5.657485,4.37538,4.19943,4.315775,4.268535,4.232149,4.26435,4.084648,4.218532,...,4.422596,4.287435,4.180138,4.412553,4.134199,4.853423,X,X,X,X
162,3.888074,5.771767,4.132832,3.896931,3.986662,4.441792,4.566333,4.305891,4.099607,4.280652,...,4.667334,4.785305,4.131191,4.281219,4.880023,4.808943,5.022344,X,X,X
163,4.773466,6.190742,4.322748,4.499781,4.572141,4.776376,4.668574,4.648151,4.933664,4.837719,...,4.583438,4.330263,4.759901,4.999361,4.448485,4.568358,4.938729,4.901204,X,X
164,4.125801,5.636983,4.18468,3.600686,4.229418,4.086531,4.10866,3.920787,3.859866,3.838568,...,3.827177,3.810868,4.013111,4.234337,3.766131,4.582436,4.326614,4.420928,4.307387,X

### <font color = blue> 5.3 Inputação dos missing values por HEOM

In [25]:
data = Dataset.builderData("hcc_dataset.csv", "?")
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
data.tratamentoMissingValues()

,Gender,Symptoms,Alcohol,HBsAg,HBeAg,HBcAb,HCVAb,Cirrhosis,Endemic,Smoking,Diabetes,Obesity,Hemochro,AHT,CRI,HIV,NASH,Varices,Spleno,PHT,PVT,Metastasis,Hallmark,Age,Grams_day,Packs_year,PS,Encephalopathy,Ascites,INR,AFP,Hemoglobin,MCV,Leucocytes,Platelets,Albumin,Total_Bil,ALT,AST,GGT,ALP,TP,Creatinine,Nodules,Major_Dim,Dir_Bil,Class
0,Male,No,Yes,No,No,No,No,Yes,No,Yes,Yes,No,Yes,No,No,No,No,Yes,No,No,No,No,Yes,67,137.000000,15.000000,Active,None,None,1.530000,9.500000e+01,13.700000,106.600000,4.900000,99.000000,3.400000,2.100000,34.000000,41.000000,183.000000,150.000000,7.100000,0.700000,1.000000,3.500000,0.500000,Lives
1,Female,No,No,No,No,No,Yes,Yes,No,No,Yes,No,No,Yes,No,No,No,Yes,No,No,No,No,Yes,62,0.000000,0.000000,Active,None,None,1.566667,2.069000e+02,10.933333,95.166667,1770.566667,55667.236667,3.440000,1.633333,65.333333,67.666667,286.666667,290.333333,6.633333,0.696667,1.000000,1.800000,0.750000,Lives
2,Male,No,Yes,Yes,No,Yes,No,Yes,No,Yes,No,No,No,Yes,Yes,No,No,No,No,Yes,No,Yes,Yes,78,50.000000,50.000000,Ambulatory,None,Mild,0.960000,5.800000e+00,8.900000,79.800000,8.400000,472.000000,3.300000,0.400000,58.000000,68.000000,202.000000,109.000000,7.000000,2.100000,5.000000,13.000000,0.100000,Lives
3,Male,Yes,Yes,No,No,No,No,Yes,No,Yes,Yes,No,No,Yes,No,No,No,No,No,No,No,Yes,Yes,77,40.000000,30.000000,Active,None,None,0.950000,2.440000e+03,13.400000,97.100000,9.000000,279.000000,3.700000,0.400000,16.000000,64.000000,94.000000,174.000000,8.100000,1.110000,2.000000,15.700000,0.200000,Dies
4,Male,Yes,Yes,Yes,No,Yes,No,Yes,No,Yes,No,No,No,Yes,Yes,No,No,No,No,No,No,No,Yes,76,100.000000,30.000000,Active,None,None,0.940000,4.900000e+01,14.300000,95.100000,6.400000,199.000000,4.100000,0.700000,147.000000,306.000000,173.000000,109.000000,6.900000,1.800000,1.000000,9.000000,0.150000,Lives
5,Male,No,Yes,No,No,No,No,Yes,No,No,No,Yes,No,No,No,No,No,Yes,Yes,Yes,No,No,Yes,75,86.666667,33.750000,Restricted,None,Mild,1.580000,1.100000e+02,13.400000,91.500000,5.400000,85.000000,3.400000,3.500000,91.000000,122.000000,242.000000,396.000000,5.600000,0.900000,1.000000,10.000000,1.400000,Dies
6,Male,No,No,No,No,Yes,Yes,Yes,No,No,Yes,No,No,No,No,No,No,No,No,No,No,No,Yes,49,0.000000,0.000000,Active,None,None,1.400000,1.389000e+02,10.400000,102.000000,3.200000,42000.000000,2.350000,2.720000,119.000000,183.000000,143.000000,211.000000,7.300000,0.800000,5.000000,2.600000,2.190000,Dies
7,Male,Yes,Yes,No,No,No,No,Yes,No,Yes,Yes,No,No,No,No,No,No,No,Yes,Yes,Yes,No,Yes,61,50.000000,20.000000,Selfcare,None,None,1.460000,9.860000e+03,10.800000,92.000000,3.000000,58.000000,3.100000,3.200000,79.000000,108.000000,184.000000,300.000000,7.100000,0.520000,2.000000,9.000000,1.300000,Dies
8,Male,Yes,Yes,No,No,No,No,Yes,No,Yes,Yes,No,No,Yes,No,No,No,Yes,Yes,Yes,No,No,Yes,50,100.000000,32.000000,Restricted,None,Mild,3.140000,8.800000e+00,11.900000,107.500000,4.900000,70.000000,1.900000,3.300000,26.000000,59.000000,115.000000,63.000000,6.100000,0.590000,1.000000,6.400000,1.200000,Lives
9,Male,Yes,Yes,No,No,No,No,Yes,No,No,No,No,Yes,No,No,No,No,No,Yes,No,No,No,No,43,100.000000,0.000000,Active,None,None,1.120000,1.800000e+00,11.800000,87.800000,5100.000000,193000.000000,4.200000,0.500000,71.000000,45.000000,256.000000,303.000000,7.100000,0.590000,1.000000,9.300000,0.700000,Lives
10,Male,No,Yes,No,No,No,Yes,Yes,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,No,No,Yes,41,95.555556,33.750000,Active,None,Mild,1.050000,1.008090e+05,13.000000,94.200000,5.700000,196.000000,4.400000,3.000000,90.000000,334.000000,494.000000,236.000000,7.600000,0.800000,5.000000,6.366667,1.100000,Dies
11,Male,No,Yes,No,No,No,Yes,Yes,Yes,No,No,No,No,Yes,No,No,No,Yes,No,Yes,No,No,Yes,74,58.518519,0.000000,Active,None,None,1.330000,8.600000e+01,15.700000,96.700000,4.000000,61.000000,3.700000,1.300000,132.000000,168.000000,113.000000,154.000000,6.844444,7.600000,5.000000,1.900000,0.300000,Lives
12,Male,No,Yes,No,No,No,No,Yes,No,Yes,Yes,No,No,Yes,No,No,No,Yes,Yes,Yes,Yes,No,No,66,130.000000,30.000000,Active,None,None,1.530000,6.000000e+01,13.300000,90.100000,5.500000,207000.000000,4.400000,8.500000,25.000000,36.000000,35.000000,74.000000,8.500000,0.730000,1.000000,5.000000,0.800000,Lives
13,Male,No,No,No,No,No,Yes,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,56,0.000000,15.666667,Active,None,None,1.200000,6.600000e+00,13.700000,93.800000,4.100000,91000.000000,4.500000,1.000000,103.000000,96.000000,205.000000,70.000000,8.800000,0.880000,1.000000,22.000000,0.250000,Lives
14,Male,No,Yes,No,No,No,No,Yes,No,Yes,Yes,No,No,Yes,No,No,No,Yes,Yes,Yes,No,No,Yes,63,90.000000,32.000000,Ambulatory,Grade I/II,Mild,1.250000,2.900000e+01,13.500000,93.000000,6.000000,128.000000,3.150000,10.500000,76.000000,116.000000,165.000000,163.000000,7.300000,1.070000,4.000000,4.500000,4.500000,Lives
15,Female,No,Yes,No,No,No,No,Yes,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,Yes,41,100.000000,0.000000,Restricted,None,Mild,1.610000,4.600000e+00,10.200000,89.600000,5.500000,161.000000,3.100000,3.100000,24.000000,57.000000,163.000000,176.000000,5.000000,0.800000,2.000000,2.600000,1.300000,Lives
16,Male,No,Yes,No,No,No,No,Yes,No,Yes,Yes,No,Yes,No,No,No,No,Yes,Yes,Yes,Yes,No,Yes,72,61.666667,37.500000,Selfcare,Grade I/II,None,2.140000,6.000000e+01,12.100000,99.200000,5.000000,58.000000,2.400000,9.800000,69.000000,63.000000,201.000000,235.000000,6.200000,0.960000,2.000000,2.000000,2.900000,Dies
17,Male,Yes,Yes,No,No,No,No,Yes,No,Yes,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,60,100.000000,60.000000,Ambulatory,None,None,1.050000,9.200000e+00,10.300000,103.700000,5.400000,159.000000,3.800000,0.500000,56.000000,91.000000,459.000000,146.000000,5.400000,1.230000,5.000000,13.500000,3.800000,Lives
18,Male,No,Yes,No,No,No,No,Yes,No,Yes,No,No,No,Yes,Yes,No,No,Yes,No,No,No,No,Yes,64,200.000000,78.000000,Restricted,None,None,1.130000,8.800000e+00,14.900000,94.800000,6.300000,137.000000,4.300000,0.900000,16.000000,23.000000,82.000000,180.000000,6.500000,4.950000,1.000000,5.400000,0.900000,Lives
19,Male,Yes,Yes,No,No,No,No,Yes,No,No,No,No,No,Yes,No,No,No,Yes,Yes,Yes,Yes,No,Yes,75,500.000000,0.000000,Active,None,Moderate/Severe,1.440000,3.400000e+01,15.900000,103.400000,9600.000000,101000.000000,3.400000,3.400000,27.000000,87.000000,260.000000,147.000000,6.300000,0.900000,5.000000,2.300000,1.600000,Dies
20,Male,No,Yes,No,No,No,No,Yes,No,Yes,No,Yes,No,No,No,No,No,Yes,Yes,Yes,No,No,No,71,200.000000,60.000000,Active,None,None,1.290000,1.960000e+01,11.700000,101.000000,2600.000000,109000.000000,3.600000,1.700000,13.000000,35.000000,23.000000,141.000000,7.300000,0.680000,1.000000,2.500000,0.700000,Lives
21,Male,No,Yes,No,No,Yes,Yes,Yes,No,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No,73,80.000000,47.000000,Active,None,None,1.060000,3.900000e+00,16.400000,90.700000,7.800000,187.000000,4.500000,1.000000,54.000000,47.000000,52.000000,97.000000,6.300000,0.750000,1.000000,6.800000,0.200000,Lives
22,Male,Yes,Yes,No,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,No,No,No,Yes,Yes,No,No,Yes,66,180.000000,0.000000,Restricted,None,Moderate/Severe,1.270000,1.975000e+03,10.800000,86.500000,9100.000000,154000.000000,3.100000,1.200000,68.000000,136.000000,869.000000,562.000000,69.000000,1.140000,5.000000,3.800000,0.500000,Dies
23,Male,Yes,Yes,No,No,No,No,Yes,Yes,Yes,Yes,No,No,Yes,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,64,200.000000,60.000000,Restricted,None,None,4.820000,1.850000e+02,10.700000,88.100000,5.000000,194000.000000,3.600000,3.800000,217.000000,86.000000,879.000000,396.000000,7.000000,0.530000,5.000000,15.000000,1.600000,Dies
24,Male,Yes,Yes,No,No,Yes,No,No,No,Yes,No,No,No,Yes,No,No,No,No,No,No,No,Yes,No,84,150.000000,27.500000,Disabled,None,None,1.740000,5.532000e+03,13.100000,111.000000,3.500000,351000.000000,2.400000,1.300000,26.000000,67.000000,108.000000,311.000000,5.600000,0.950000,1.000000,10.000000,0.700000,Dies
25,Male,No,Yes,No,No,No,No,Yes,No,No,Yes,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,Yes,80,100.000000,0.000000,Ambulatory,None,None,1.330000,1.332700e+04,13.700000,94.300000,5.200000,110.000000,3.100000,1.600000,52.000000,107.000000,465.000000,233.000000,8.400000,0.790000,5.000000,7.533333,0.700000,Lives
26,Male,Yes,Yes,No,No,No,Yes,Yes,No,Yes,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,Yes,45,50.000000,16.000000,Restricted,None,Moderate/Severe,1.380000,1.817267e+04,13.600000,98.400000,4.300000,99000.000000,3.300000,1.300000,178.000000,325.000000,252.000000,172.000000,8.100000,0.830000,1.000000,5.000000,0.700000,Dies
27,Male,Yes,Yes,Yes,No,Yes,No,Yes,No,Yes,No,No,No,No,No,No,No,Yes,Yes,Yes,No,No,Yes,57,80.000000,20.000000,Active,None,None,1.370000,5.900000e+00,15.500000,88.200000,4.900000,113.000000,4.500000,3.200000,36.000000,65.000000,34.000000,111.000000,17.466667,0.583333,2.000000,4.000000,1.000000,Lives
28,Male,No,Yes,No,No,No,No,Yes,No,Yes,Yes,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,Yes,61,60.000000,67.500000,Restricted,None,None,1.300000,3.255000e+03,12.200000,89.500000,4.400000,108.000000,3.000000,1.100000,59.000000,85.000000,419.000000,293.000000,7.700000,0.670000,2.000000,6.500000,0.400000,Dies
29,Male,Yes,Yes,No,No,No,No,Yes,No,Yes,No,No,No,No,No,No,No,No,No,No,No,No,Yes,20,113.333333,2.000000,Restricted,None,None,1.210000,1.900000e+00,9.900000,83.400000,8.100000,556.000000,3.200000,1.800000,150.000000,112.000000,599.000000,974.000000,7.700000,0.700000,5.000000,10.133333,1.100000,Lives
30,Male,Yes,Yes,Yes,No,No,No,Yes,Yes,Yes,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,Yes,60,20.000000,8.000000,Ambulatory,None,None,1.190000,1.100000e+01,13.100000,87.900000,7.800000,212.000000,3.500000,0.700000,27.000000,26.000000,143.000000,158.000000,8.200000,0.710000,1.000000,16.000000,1.766667,Lives
31,Male,No,Yes,No,No,No,No,Yes,No,Yes,Yes,No,No,Yes,No,No,No,Yes,Yes,Yes,No,No,Yes,62,120.000000,45.000000,Active,None,None,1.440000,1.237000e+03,12.200000,94.000000,6200.000000,93000.000000,4.200000,1.000000,35.000000,85.000000,191.000000,129.000000,58.000000,1.060000,5.000000,7.000000,0.783333,Lives
32,Male,Yes,Yes,No,No,No,No,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,67,100.000000,15.000000,Active,None,None,1.320000,7.700000e+00,15.700000,96.100000,9.100000,268000.000000,3.400000,0.600000,20.000000,29.000000,49.000000,135.000000,8.200000,0.900000,2.000000,7.500000,0.225000,Lives
33,Male,Yes,Yes,No,No,No,No,Yes,No,No,No,No,No,Yes,No,No,No,No,No,No,No,No,Yes,77,100.000000,5.000000,Active,None,None,1.240000,2.660000e+02,13.700000,97.700000,13000.000000,170000.000000,4.200000,0.500000,68.000000,85.000000,232.000000,227.000000,16.800000,1.720000,1.000000,5.900000,0.262500,Lives
34,Male,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,No,Yes,No,No,No,Yes,No,Yes,No,No,No,62,93.333333,0.000000,Active,None,None,1.280000,5.689000e+03,14.300000,99.600000,6.800000,77.000000,3.800000,1.700000,154.000000,102.000000,184.000000,184.000000,6.900000,0.890000,2.000000,3.000000,0.770000,Lives
35,Male,Yes,No,Yes,No,Yes,No,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,No,76,0.000000,0.000000,Active,None,None,0.960000,1.420000e+01,14.800000,98.500000,4.950000,187.000000,4.200000,0.770000,43.000000,86.000000,89.000000,113.000000,6.700000,0.950000,3.000000,8.800000,0.370000,Lives
36,Male,Yes,Yes,No,No,No,No,Yes,No,No,Yes,No,No,Yes,No,No,No,Yes,Yes,Yes,No,No,Yes,73,75.000000,0.000000,Disabled,None,Mild,2.000000,3.100000e+00,13.100000,109.300000,44.600000,60.000000,2.300000,7.800000,38.000000,74.000000,180.000000,127.000000,5.600000,0.880000,5.000000,3.100000,3.300000,Dies
37,Male,Yes,Yes,No,No,No,No,Yes,No,Yes,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,No,Yes,84,200.000000,30.000000,Restricted,None,Mild,1.240000,6.330000e+02,13.000000,96.500000,7200.000000,143000.000000,2.300000,1.100000,40.000000,58.000000,322.000000,209.000000,6.700000,1.400000,5.000000,4.900000,0.200000,Dies
38,Male,No,Yes,No,No,No,No,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,70,100.000000,0.000000,Active,None,None,1.090000,5.400000e+00,14.900000,105.000000,7.200000,230000.000000,4.200000,1.300000,18.000000,26.000000,174.000000,92.000000,7.300000,0.800000,2.000000,6.000000,0.300000,Lives
39,Male,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,No,No,No,No,Yes,No,No,No,No,No,No,No,Yes,Yes,59,200.000000,0.000000,Active,None,None,1.420000,4.790000e+02,11.300000,82.200000,9500.000000,160000.000000,3.100000,1.400000,113.000000,143.000000,924.000000,288.000000,7.900000,0.980000,5.000000,17.000000,0.600000,Lives
40,Female,No,No,No,No,Yes,Yes,Yes,No,No,No,No,No,Yes,No,No,No,No,No,No,No,No,Yes,71,0.000000,0.000000,Active,None,None,1.180000,1.900000e+01,13.900000,88.300000,6.860000,201000.000000,4.400000,0.800000,142.000000,117.000000,123.000000,104.000000,8.500000,0.740000,2.000000,3.300000,0.300000,Lives
41,Male,No,No,No,No,Yes,No,Yes,No,No,Yes,Yes,No,Yes,No,No,No,No,No,No,No,No,No,66,0.000000,0.000000,Active,None,None,1.210000,2.800000e+00,15.700000,92.700000,15.400000,188000.000000,4.100000,0.700000,299.000000,553.000000,196.000000,68.000000,6.500000,1.300000,1.000000,5.000000,0.300000,Lives
42,Female,No,Yes,No,No,No,No,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,No,86,66.666667,0.000000,Selfcare,None,None,1.200000,1.852030e+05,15.000000,85.500000,8.800000,183.000000,3.600000,1.000000,49.000000,117.000000,442.000000,278.000000,7.200000,0.860000,5.000000,15.800000,0.300000,Dies
43,Male,No,Yes,No,No,No,No,Yes,No,Yes,No,Yes,No,No,No,No,Yes,Yes,Yes,Yes,No,No,Yes,71,75.000000,40.000000,Active,None,None,1.170000,5.000000e+00,15.100000,104.100000,4.300000,65000.000000,3.800000,2.500000,61.000000,56.000000,239.000000,56.000000,7.300000,0.700000,1.000000,2.000000,0.200000,Lives
44,Female,No,No,No,No,Yes,Yes,Yes,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,No,No,Yes,52,0.000000,0.000000,Active,None,None,1.710000,2.370000e+02,15.600000,98.100000,4.300000,88.000000,3.200000,2.200000,30.000000,52.000000,72.000000,97.000000,6.700000,0.860000,5.000000,2.200000,0.500000,Lives
45,Male,No,Yes,No,No,No,No,Yes,No,No,Yes,No,No,No,No,No,Yes,No,No,No,No,No,Yes,60,100.000000,0.000000,Active,None,None,1.180000,2.800000e+00,16.600000,93.800000,8300.000000,167000.000000,4.900000,0.900000,35.000000,29.000000,62.000000,68.000000,8.300000,0.720000,1.000000,2.300000,0.308333,Lives
46,Female,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,45,0.000000,0.000000,Active,None,None,1.106667,2.390000e+01,13.133333,88.100000,10.866667,134750.333333,3.366667,0.566667,23.000000,81.000000,74.000000,271.666667,6.800000,0.710000,2.666667,12.333333,0.262500,Lives
47,Male,Yes,Yes,No,No,No,No,Yes,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,Yes,No,66,75.000000,22.833333,Restricted,None,Mild,1.640000,1.600000e+01,14.000000,102.900000,11.500000,277000.000000,3.100000,6.800000,140.000000,244.000000,795.000000,595.000000,7.200000,0.790000,1.000000,2.300000,4.100000,Dies
48,Male,Yes,No,No,No,No,No,No,No,Yes,Yes,No,No,Yes,Yes,No,Yes,No,No,No,No,No,No,80,0.000000,80.000000,Active,None,None,1.330000,1.630000e+02,10.600000,96.200000,9900.000000,280000.000000,3.300000,1.000000,28.000000,57.000000,236.000000,171.000000,7.500000,1.380000,1.000000,19.000000,0.200000,Dies
49,Male,No,Yes,No,No,Yes,No,Yes,No,Yes,No,No,No,No,No,No,No,Yes,Yes,Yes,No,No,No,58,113.333333,40.000000,Active,None,None,1.490000,2.000000e+01,15.000000,96.700000,9.000000,78.000000,4.600000,2.100000,40.000000,49.000000,137.000000,109.000000,7.600000,0.800000,1.000000,2.000000,0.400000,Lives
50,Female,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,Yes,27,0.000000,0.000000,Ambulatory,None,None,0.970000,4.600000e+01,10.500000,78.700000,20.900000,251.000000,2.400000,0.300000,31.000000,185.000000,91.000000,539.000000,5.000000,0.380000,5.000000,20.000000,0.300000,Dies
51,Female,No,Yes,No,No,No,Yes,Yes,No,No,Yes,No,No,No,No,No,No,Yes,Yes,Yes,No,Yes,No,73,100.000000,0.000000,Active,None,None,1.200000,4.147000e+04,12.600000,91.400000,12.000000,275000.000000,3.110000,2.300000,55.000000,94.000000,394.000000,350.000000,7.300000,1.700000,5.000000,8.666667,0.800000,Dies
52,Male,Yes,Yes,No,No,No,No,Yes,No,No,Yes,No,No,Yes,No,No,No,No,No,No,No,No,No,73,80.000000,0.000000,Active,None,None,1.330000,4.700000e+00,11.800000,80.200000,3.700000,99.000000,4.100000,0.700000,50.000000,47.000000,67.000000,62.000000,7.400000,0.770000,1.000000,2.300000,0.229167,Lives
53,Male,No,Yes,No,No,No,No,Yes,No,No,No,No,Yes,No,No,No,No,Yes,Yes,Yes,No,No,Yes,50,93.333333,0.000000,Active,None,None,1.650000,7.300000e+00,15.300000,93.700000,3500.000000,57000.000000,3.600000,1.400000,111.000000,93.000000,294.000000,130.000000,20.522222,0.760000,2.000000,2.000000,0.300000,Lives
54,Male,Yes,Yes,No,No,No,Yes,Yes,No,Yes,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,Yes,51,100.000000,30.000000,Selfcare,None,Mild,1.350000,1.898000e+03,12.400000,95.100000,9.800000,216.000000,2.700000,8.200000,164.000000,523.000000,433.000000,397.000000,6.700000,0.820000,1.000000,2.100000,5.500000,Dies
55,Female,Yes,No,No,No,No,Yes,No,No,No,Yes,No,No,Yes,No,No,No,No,No,No,No,Yes,Yes,78,0.000000,0.000000,Restricted,None,None,1.320000,7.700000e+01,10.800000,88.000000,6000.000000,174000.000000,3.200000,0.900000,48.000000,19.000000,171.000000,923.000000,5.400000,1.310000,3.000000,15.400000,0.300000,Dies
56,Male,Yes,Yes,No,No,No,No,Yes,No,Yes,Yes,No,No,Yes,No,No,No,No,No,Yes,No,No,Yes,81,100.000000,10.000000,Ambulatory,None,Mild,3.560000,2.700000e+00,7.300000,90.800000,2.420000,159000.000000,3.400000,0.500000,25.000000,32.000000,80.000000,55.000000,6.200000,0.850000,1.000000,2.200000,0.533333,Dies
57,Male,No,Yes,No,No,No,No,Yes,No,Yes,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,No,Yes,65,100.000000,30.000000,Active,None,None,1.240000,2.600000e+00,10.300000,83.000000,6.100000,1.710000,3.900000,0.800000,11.000000,28.000000,77.000000,120.000000,7.000000,0.580000,1.000000,4.700000,0.850000,Lives
58,Male,Yes,Yes,No,No,No,No,Yes,No,No,Yes,No,No,No,No,No,No,Yes,Yes,Yes,No,No,Yes,72,70.000000,0.000000,Selfcare,Grade I/II,Mild,1.960000,1.200000e+01,10.900000,102.000000,4.100000,99.000000,1.900000,4.200000,73.000000,85.000000,470.000000,263.000000,7.000000,0.990000,1.000000,8.500000,1.900000,Dies
59,Male,Yes,No,No,No,No,No,No,No,Yes,Yes,No,No,Yes,Yes,No,No,No,No,No,No,No,No,82,0.000000,36.666667,Active,None,None,1.110000,8.684667e+02,18.700000,92.400000,6900.000000,270000.000000,4.000000,0.900000,35.000000,73.000000,115.000000,103.000000,6.800000,1.240000,1.000000,10.000000,0.200000,Dies
60,Male,Yes,No,Yes,No,Yes,No,Yes,Yes,Yes,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,Yes,76,0.000000,50.000000,Restricted,None,Moderate/Severe,1.280000,6.080000e+02,12.600000,100.000000,5.400000,129.000000,4.000000,1.700000,107.000000,99.000000,125.000000,100.000000,7.500000,0.900000,5.000000,3.500000,0.500000,Lives
61,Male,Yes,Yes,No,No,Yes,Yes,Yes,No,Yes,No,No,No,No,No,No,No,Yes,Yes,Yes,No,No,Yes,56,100.000000,40.000000,Active,Grade I/II,Mild,1.460000,4.100000e+01,14.600000,100.800000,5.500000,42000.000000,3.100000,3.700000,121.000000,165.000000,101.000000,207.000000,6.300000,0.690000,1.000000,3.000000,1.900000,Lives
62,Female,No,Yes,No,No,No,No,Yes,No,Yes,No,Yes,No,No,No,No,No,Yes,Yes,Yes,No,No,Yes,68,128.888889,30.000000,Ambulatory,None,Mild,1.940000,4.473333e+01,11.500000,97.400000,5700.000000,77000.000000,2.700000,4.900000,34.000000,48.000000,46.000000,178.000000,6.100000,0.620000,1.000000,4.600000,2.200000,Lives
63,Male,Yes,Yes,No,No,No,No,Yes,No,Yes,Yes,No,No,Yes,No,No,No,Yes,Yes,Yes,No,No,Yes,72,300.000000,35.666667,Selfcare,None,Moderate/Severe,1.570000,2.000000e+00,12.600000,96.600000,2.900000,76000.000000,3.500000,2.400000,33.000000,40.000000,110.000000,166.000000,23.700000,0.770000,1.000000,2.000000,0.500000,Lives
64,Male,No,No,No,No,No,No,No,No,No,Yes,No,No,Yes,No,No,No,No,No,No,No,No,No,66,0.000000,0.000000,Active,None,None,1.290000,7.000000e+00,12.100000,95.100000,3.800000,77000.000000,3.800000,1.400000,37.000000,38.000000,194.000000,161.000000,6.700000,0.710000,1.000000,10.000000,0.500000,Lives

# <font color = darkblue> 6. Ajuste dos outliers

### <font color = blue> 6.1.Identificação visual dos outliers

In [6]:
data = Dataset.builderData("hcc_dataset.csv", "?")
display(data.outliers('style'))

In [15]:
data = Dataset.builderData("hcc_dataset.csv", "?")
display(data.outliers('index'))

ValueError: could not convert string to float: 'Male'

In [74]:
data = Dataset.builderData("hcc_dataset.csv", "?")
display(data.polirTabela())

,Age,Grams_day,Packs_year,INR,AFP,Hemoglobin,MCV,Leucocytes,Platelets,Albumin,Total_Bil,ALT,AST,GGT,ALP,TP,Creatinine,Nodules,Major_Dim,Dir_Bil
0,67,137.000000,15.000000,1.530000,9.500000e+01,13.700000,106.600000,4.900000,99.000000,3.400000,2.100000,34.000000,41.000000,183.000000,150.000000,7.100000,0.700000,1.000000,3.500000,0.500000
1,62,0.000000,0.000000,1.186667,1.637933e+03,14.600000,93.466667,8.166667,94713.666667,3.733333,1.900000,185.333333,267.333333,153.000000,144.000000,6.800000,0.966667,1.000000,1.800000,0.966667
2,78,50.000000,50.000000,0.960000,5.800000e+00,8.900000,79.800000,8.400000,472.000000,3.300000,0.400000,58.000000,68.000000,202.000000,109.000000,7.000000,2.100000,5.000000,13.000000,0.100000
3,77,40.000000,30.000000,0.950000,2.440000e+03,13.400000,97.100000,9.000000,279.000000,3.700000,0.400000,16.000000,64.000000,94.000000,174.000000,8.100000,1.110000,2.000000,15.700000,0.200000
4,76,100.000000,30.000000,0.940000,4.900000e+01,14.300000,95.100000,6.400000,199.000000,4.100000,0.700000,147.000000,306.000000,173.000000,109.000000,6.900000,1.800000,1.000000,9.000000,0.350000
5,75,30.000000,29.166667,1.580000,1.100000e+02,13.400000,91.500000,5.400000,85.000000,3.400000,3.500000,91.000000,122.000000,242.000000,396.000000,5.600000,0.900000,1.000000,10.000000,1.400000
6,49,0.000000,0.000000,1.400000,1.389000e+02,10.400000,102.000000,3.200000,42000.000000,2.350000,2.720000,119.000000,183.000000,143.000000,211.000000,7.300000,0.800000,5.000000,2.600000,2.190000
7,61,53.333333,20.000000,1.460000,9.860000e+03,10.800000,92.000000,3.000000,58.000000,3.100000,3.200000,79.000000,108.000000,184.000000,300.000000,7.100000,0.520000,2.000000,9.000000,1.300000
8,50,100.000000,32.000000,3.140000,8.800000e+00,11.900000,107.500000,4.900000,70.000000,1.900000,3.300000,26.000000,59.000000,115.000000,63.000000,6.100000,0.590000,1.000000,6.400000,1.200000
9,43,100.000000,0.000000,1.120000,1.800000e+00,11.800000,87.800000,5100.000000,193000.000000,4.200000,0.500000,71.000000,45.000000,256.000000,303.000000,7.100000,0.590000,1.000000,9.300000,0.700000
10,41,50.000000,55.000000,1.050000,1.008090e+05,13.000000,94.200000,5.700000,196.000000,4.400000,3.000000,90.000000,334.000000,494.000000,236.000000,7.600000,0.800000,5.000000,7.166667,1.100000
11,74,125.000000,0.000000,1.330000,8.600000e+01,15.700000,96.700000,4.000000,61.000000,3.700000,1.300000,132.000000,168.000000,113.000000,154.000000,6.133333,7.600000,5.000000,1.900000,0.300000
12,66,33.333333,30.000000,1.530000,6.000000e+01,13.300000,90.100000,5.500000,207000.000000,4.400000,8.500000,25.000000,36.000000,35.000000,74.000000,8.500000,0.730000,1.000000,5.000000,0.800000
13,56,0.000000,0.000000,1.200000,6.600000e+00,13.700000,93.800000,4.100000,91000.000000,4.500000,1.000000,103.000000,96.000000,205.000000,70.000000,8.800000,0.880000,1.000000,22.000000,0.500000
14,63,200.000000,20.000000,1.250000,2.900000e+01,13.500000,93.000000,6.000000,128.000000,3.150000,10.500000,76.000000,116.000000,165.000000,163.000000,7.300000,1.070000,4.000000,4.500000,4.500000
15,41,100.000000,0.000000,1.610000,4.600000e+00,10.200000,89.600000,5.500000,161.000000,3.100000,3.100000,24.000000,57.000000,163.000000,176.000000,5.000000,0.800000,2.000000,2.600000,1.300000
16,72,100.000000,14.000000,2.140000,6.000000e+01,12.100000,99.200000,5.000000,58.000000,2.400000,9.800000,69.000000,63.000000,201.000000,235.000000,6.200000,0.960000,2.000000,2.000000,2.900000
17,60,100.000000,60.000000,1.050000,9.200000e+00,10.300000,103.700000,5.400000,159.000000,3.800000,0.500000,56.000000,91.000000,459.000000,146.000000,5.400000,1.230000,5.000000,13.500000,3.800000
18,64,200.000000,78.000000,1.130000,8.800000e+00,14.900000,94.800000,6.300000,137.000000,4.300000,0.900000,16.000000,23.000000,82.000000,180.000000,6.500000,4.950000,1.000000,5.400000,0.900000
19,75,500.000000,10.000000,1.440000,3.400000e+01,15.900000,103.400000,9600.000000,101000.000000,3.400000,3.400000,27.000000,87.000000,260.000000,147.000000,6.300000,0.900000,5.000000,2.300000,1.600000
20,71,200.000000,60.000000,1.290000,1.960000e+01,11.700000,101.000000,2600.000000,109000.000000,3.600000,1.700000,13.000000,35.000000,23.000000,141.000000,7.300000,0.680000,1.000000,2.500000,0.700000
21,73,80.000000,47.000000,1.060000,3.900000e+00,16.400000,90.700000,7.800000,187.000000,4.500000,1.000000,54.000000,47.000000,52.000000,97.000000,6.300000,0.750000,1.000000,6.800000,0.200000
22,66,180.000000,0.000000,1.270000,1.975000e+03,10.800000,86.500000,9100.000000,154000.000000,3.100000,1.200000,68.000000,136.000000,869.000000,562.000000,69.000000,1.140000,5.000000,3.800000,0.500000
23,64,200.000000,60.000000,4.820000,1.850000e+02,10.700000,88.100000,5.000000,194000.000000,3.600000,3.800000,217.000000,86.000000,879.000000,396.000000,7.000000,0.530000,5.000000,15.000000,1.600000
24,84,150.000000,12.500000,1.740000,5.532000e+03,13.100000,111.000000,3.500000,351000.000000,2.400000,1.300000,26.000000,67.000000,108.000000,311.000000,5.600000,0.950000,1.000000,10.000000,0.700000
25,80,100.000000,0.000000,1.330000,1.332700e+04,13.700000,94.300000,5.200000,110.000000,3.100000,1.600000,52.000000,107.000000,465.000000,233.000000,8.400000,0.790000,5.000000,8.333333,0.700000
26,45,50.000000,16.000000,1.380000,2.290000e+01,13.600000,98.400000,4.300000,99000.000000,3.300000,1.300000,178.000000,325.000000,252.000000,172.000000,8.100000,0.830000,1.000000,5.000000,0.700000
27,57,130.000000,59.000000,1.370000,5.900000e+00,15.500000,88.200000,4.900000,113.000000,4.500000,3.200000,36.000000,65.000000,34.000000,111.000000,7.300000,2.100000,2.000000,4.000000,1.000000
28,61,60.000000,67.500000,1.300000,3.255000e+03,12.200000,89.500000,4.400000,108.000000,3.000000,1.100000,59.000000,85.000000,419.000000,293.000000,7.700000,0.670000,2.000000,6.500000,0.400000
29,20,80.000000,2.000000,1.210000,1.900000e+00,9.900000,83.400000,8.100000,556.000000,3.200000,1.800000,150.000000,112.000000,599.000000,974.000000,7.700000,0.700000,5.000000,6.033333,1.100000
30,60,20.000000,8.000000,1.190000,1.100000e+01,13.100000,87.900000,7.800000,212.000000,3.500000,0.700000,27.000000,26.000000,143.000000,158.000000,8.200000,0.710000,1.000000,16.000000,0.350000
31,62,120.000000,16.666667,1.440000,1.237000e+03,12.200000,94.000000,6200.000000,93000.000000,4.200000,1.000000,35.000000,85.000000,191.000000,129.000000,58.000000,1.060000,5.000000,7.000000,1.100000
32,67,100.000000,178.333333,1.320000,7.700000e+00,15.700000,96.100000,9.100000,268000.000000,3.400000,0.600000,20.000000,29.000000,49.000000,135.000000,8.200000,0.900000,2.000000,6.433333,1.600000
33,77,71.008547,10.000000,1.240000,2.660000e+02,13.700000,97.700000,13000.000000,170000.000000,4.200000,0.500000,68.000000,85.000000,232.000000,227.000000,16.800000,1.720000,1.000000,5.900000,0.300000
34,62,56.666667,0.000000,1.280000,5.689000e+03,14.300000,99.600000,6.800000,77.000000,3.800000,1.700000,154.000000,102.000000,184.000000,184.000000,6.900000,0.890000,2.000000,3.000000,0.770000
35,76,0.000000,0.000000,0.960000,1.420000e+01,14.800000,98.500000,4.950000,187.000000,4.200000,0.770000,43.000000,86.000000,89.000000,113.000000,6.700000,0.950000,3.000000,8.800000,0.370000
36,73,75.000000,0.000000,2.000000,3.100000e+00,13.100000,109.300000,44.600000,60.000000,2.300000,7.800000,38.000000,74.000000,180.000000,127.000000,5.600000,0.880000,5.000000,3.100000,3.300000
37,84,200.000000,30.000000,1.240000,6.330000e+02,13.000000,96.500000,7200.000000,143000.000000,2.300000,1.100000,40.000000,58.000000,322.000000,209.000000,6.700000,1.400000,5.000000,4.900000,0.200000
38,70,100.000000,0.000000,1.090000,5.400000e+00,14.900000,105.000000,7.200000,230000.000000,4.200000,1.300000,18.000000,26.000000,174.000000,92.000000,7.300000,0.800000,2.000000,6.000000,0.300000
39,59,200.000000,0.000000,1.420000,4.790000e+02,11.300000,82.200000,9500.000000,160000.000000,3.100000,1.400000,113.000000,143.000000,924.000000,288.000000,7.900000,0.980000,5.000000,17.000000,0.600000
40,71,0.000000,0.000000,1.180000,1.900000e+01,13.900000,88.300000,6.860000,201000.000000,4.400000,0.800000,142.000000,117.000000,123.000000,104.000000,8.500000,0.740000,2.000000,3.300000,0.300000
41,66,0.000000,0.000000,1.210000,2.800000e+00,15.700000,92.700000,15.400000,188000.000000,4.100000,0.700000,299.000000,553.000000,196.000000,68.000000,6.500000,1.300000,1.000000,5.000000,0.300000
42,86,66.666667,32.666667,1.200000,1.852030e+05,15.000000,85.500000,8.800000,183.000000,3.600000,1.000000,49.000000,117.000000,442.000000,278.000000,7.200000,0.860000,5.000000,15.800000,0.300000
43,71,75.000000,15.000000,1.170000,5.000000e+00,15.100000,104.100000,4.300000,65000.000000,3.800000,2.500000,61.000000,56.000000,239.000000,56.000000,7.300000,0.700000,1.000000,2.000000,0.200000
44,52,0.000000,0.000000,1.710000,2.370000e+02,15.600000,98.100000,4.300000,88.000000,3.200000,2.200000,30.000000,52.000000,72.000000,97.000000,6.700000,0.860000,5.000000,2.200000,0.500000
45,60,50.000000,0.000000,1.180000,2.800000e+00,16.600000,93.800000,8300.000000,167000.000000,4.900000,0.900000,35.000000,29.000000,62.000000,68.000000,8.300000,0.720000,1.000000,2.300000,0.433333
46,45,0.000000,0.000000,1.356667,1.078667e+02,12.266667,93.300000,2233.466667,103376.666667,2.983333,1.180000,78.333333,95.000000,150.666667,343.333333,6.600000,0.700000,3.666667,8.200000,1.155000
47,66,91.666667,27.500000,1.640000,1.600000e+01,14.000000,102.900000,11.500000,277000.000000,3.100000,6.800000,140.000000,244.000000,795.000000,595.000000,7.200000,0.790000,1.000000,2.300000,4.100000
48,80,0.000000,80.000000,1.330000,1.630000e+02,10.600000,96.200000,9900.000000,280000.000000,3.300000,1.000000,28.000000,57.000000,236.000000,171.000000,7.500000,1.380000,1.000000,19.000000,1.930000
49,58,140.000000,40.000000,1.490000,2.000000e+01,15.000000,96.700000,9.000000,78.000000,4.600000,2.100000,40.000000,49.000000,137.000000,109.000000,7.600000,0.800000,1.000000,2.000000,0.400000
50,27,0.000000,0.000000,0.970000,4.600000e+01,10.500000,78.700000,20.900000,251.000000,2.400000,0.300000,31.000000,185.000000,91.000000,539.000000,5.000000,0.380000,5.000000,20.000000,0.300000
51,73,100.000000,0.000000,1.200000,4.147000e+04,12.600000,91.400000,12.000000,275000.000000,3.110000,2.300000,55.000000,94.000000,394.000000,350.000000,7.300000,1.700000,5.000000,6.450000,0.800000
52,73,40.000000,0.000000,1.330000,4.700000e+00,11.800000,80.200000,3.700000,99.000000,4.100000,0.700000,50.000000,47.000000,67.000000,62.000000,7.400000,0.770000,1.000000,2.300000,0.650000
53,50,30.000000,0.000000,1.650000,7.300000e+00,15.300000,93.700000,3500.000000,57000.000000,4.000000,1.400000,111.000000,93.000000,294.000000,130.000000,7.933333,0.760000,2.000000,2.000000,0.300000
54,51,100.000000,30.000000,1.350000,1.898000e+03,12.400000,95.100000,9.800000,216.000000,2.700000,8.200000,164.000000,523.000000,433.000000,397.000000,6.700000,0.820000,1.000000,2.100000,5.500000
55,78,0.000000,0.000000,1.320000,7.700000e+01,10.800000,88.000000,6000.000000,174000.000000,3.200000,0.900000,48.000000,19.000000,171.000000,923.000000,5.400000,1.310000,3.000000,15.400000,1.460000
56,81,100.000000,10.000000,3.560000,2.700000e+00,7.300000,90.800000,2.420000,159000.000000,3.400000,0.500000,25.000000,32.000000,80.000000,55.000000,6.200000,0.850000,1.000000,2.200000,0.933333
57,65,100.000000,0.000000,1.240000,2.600000e+00,10.300000,83.000000,6.100000,1.710000,3.900000,0.800000,11.000000,28.000000,77.000000,120.000000,7.000000,0.580000,1.000000,4.700000,0.850000
58,72,70.000000,0.000000,1.960000,1.200000e+01,10.900000,102.000000,4.100000,99.000000,1.900000,4.200000,73.000000,85.000000,470.000000,263.000000,7.000000,0.990000,1.000000,8.500000,1.900000
59,82,0.000000,0.000000,1.110000,1.173333e+01,18.700000,92.400000,6900.000000,270000.000000,4.000000,0.900000,35.000000,73.000000,115.000000,103.000000,6.800000,1.240000,1.000000,10.000000,0.300000
60,76,0.000000,50.000000,1.280000,6.080000e+02,12.600000,100.000000,5.400000,129.000000,4.000000,1.700000,107.000000,99.000000,125.000000,100.000000,7.500000,0.900000,5.000000,3.500000,0.500000
61,56,100.000000,40.000000,1.460000,4.100000e+01,14.600000,100.800000,5.500000,42000.000000,3.100000,3.700000,121.000000,165.000000,101.000000,207.000000,6.300000,0.690000,1.000000,3.000000,1.900000
62,68,200.000000,30.000000,1.940000,3.276667e+01,11.500000,97.400000,5700.000000,77000.000000,2.700000,4.900000,34.000000,48.000000,46.000000,178.000000,6.100000,0.620000,1.000000,4.600000,2.200000
63,72,300.000000,32.666667,1.570000,2.000000e+00,12.600000,96.600000,2.900000,76000.000000,3.500000,2.400000,33.000000,40.000000,110.000000,166.000000,7.500000,0.770000,1.000000,2.000000,0.500000
64,66,0.000000,0.000000,1.290000,7.000000e+00,12.100000,95.100000,3.800000,77000.000000,3.800000,1.400000,37.000000,38.000000,194.000000,161.000000,6.700000,0.710000,1.000000,10.000000,0.500000
65,40,0.000000,0.000000,1.170000,3.100000e+00,15.100000,86.000000,8.900000,275000.000000,2.800000,1.300000,74.000000,50.000000,23.000000,104.000000,5.400000,0.600000,5.000000,7.800000,0.200000
66,68,60.000000,15.666667,1.340000,1.300000e+01,15.600000,93.000000,4.900000,91000.000000,4.540000,1.400000,54.000000,52.000000,275.000000,113.000000,7.800000,0.550000,2.000000,6.200000,0.300000
67,63,100.000000,0.000000,2.070000,1.700000e+00,9.500000,99.200000,3300.000000,79000.000000,2.100000,1.600000,56.000000,82.000000,134.000000,113.000000,37.000000,0.400000,1.000000,2.700000,0.200000
68,72,100.000000,0.000000,1.300000,2.490000e+02,12.700000,100.300000,5.500000,114.000000,3.100000,3.900000,21.000000,42.000000,40.000000,108.000000,5.800000,0.900000,5.000000,8.000000,1.200000
69,88,80.000000,0.000000,1.270000,6.600000e+01,10.900000,97.300000,8.900000,270.000000,2.700000,2.100000,145.000000,84.000000,179.000000,260.000000,5.900000,1.056667,5.000000,3.000000,1.300000
70,23,0.000000,0.000000,1.170000,3.580000e+02,12.700000,74.000000,2.200000,51.000000,2.900000,2.800000,53.000000,41.000000,54.000000,94.000000,4.900000,0.200000,2.000000,5.400000,0.800000
71,59,75.000000,44.000000,1.010000,1.810346e+06,13.000000,102.100000,8300.000000,433000.000000,3.400000,1.900000,138.000000,86.000000,1575.000000,417.000000,6.500000,0.640000,5.000000,15.000000,1.100000
72,82,50.000000,48.000000,1.530000,3.350200e+04,14.400000,101.100000,11.600000,109.000000,3.100000,2.300000,27.000000,80.000000,177.000000,1.280000,6.700000,1.500000,5.000000,4.000000,0.800000
73,67,66.666667,0.000000,0.940000,2.000000e+01,13.000000,92.000000,6.900000,222000.000000,3.700000,0.600000,162.000000,354.000000,1390.000000,684.000000,7.100000,0.810000,5.000000,12.550000,0.550000
74,61,83.333333,15.000000,1.150000,2.500000e+00,14.900000,92.300000,6.000000,159000.000000,3.800000,1.000000,28.000000,38.000000,74.000000,101.000000,7.400000,1.100000,5.000000,7.500000,0.300000
75,61,100.000000,32.500000,1.920000,2.269000e+03,12.100000,119.000000,5.100000,80000.000000,3.346667,9.600000,204.000000,357.000000,199.000000,174.000000,6.833333,0.990000,1.000000,7.600000,4.600000
76,67,100.000000,20.000000,3.160000,4.181000e+03,9.100000,103.600000,5.100000,128000.000000,3.000000,2.200000,57.000000,91.000000,115.000000,165.000000,7.700000,0.830000,1.000000,4.500000,1.200000
77,78,80.000000,33.333333,1.450000,5.100000e+00,14.400000,100.200000,7.100000,77000.000000,4.100000,0.900000,43.000000,63.000000,540.000000,114.000000,7.000000,1.090000,5.000000,2.750000,0.600000
78,52,80.000000,16.666667,1.340000,3.450000e+02,9.800000,81.800000,13.600000,561.000000,2.600000,0.500000,43.000000,43.000000,23.000000,88.000000,5.600000,1.256667,5.000000,4.700000,0.500000
79,51,100.000000,34.500000,2.080000,2.900000e+00,10.400000,91.100000,5.800000,91000.000000,2.400000,16.000000,123.000000,145.000000,109.000000,190.000000,5.900000,0.900000,0.000000,3.066667,9.600000
80,74,0.000000,7.500000,1.320000,2.500000e+00,12.600000,83.700000,9.800000,102000.000000,3.300000,1.200000,29.000000,43.000000,196.000000,204.000000,7.300000,1.100000,5.000000,9.666667,0.500000
81,56,100.000000,20.000000,1.630000,5.040000e+00,15.800000,99.000000,5.800000,75000.000000,3.500000,4.600000,93.000000,85.000000,193.000000,165.000000,6.600000,0.700000,1.000000,6.000000,1.700000
82,64,100.000000,0.000000,1.710000,3.700000e+00,14.800000,104.300000,5.800000,56000.000000,2.700000,2.600000,74.000000,157.000000,311.000000,280.000000,8.000000,0.800000,2.000000,3.000000,1.400000
83,83,100.000000,48.500000,1.480000,2.600000e+00,12.700000,106.000000,3.800000,80.000000,2.900000,3.400000,34.000000,53.000000,156.000000,207.000000,7.200000,2.203333,2.000000,4.100000,1.400000
84,57,0.000000,7.500000,1.100000,2.900000e+00,16.400000,94.800000,4.600000,94000.000000,4.100000,1.100000,104.000000,74.000000,88.000000,85.000000,7.900000,1.050000,1.000000,5.500000,0.300000
85,58,100.000000,10.000000,1.470000,2.000000e+01,13.900000,100.800000,4.000000,112000.000000,3.000000,2.900000,50.000000,92.000000,124.000000,244.000000,6.300000,0.800000,2.000000,6.800000,0.700000
86,71,160.000000,30.000000,1.080000,2.790000e+00,12.600000,83.900000,7100.000000,284000.000000,3.233333,0.966667,28.000000,46.000000,70.000000,213.000000,23.666667,0.480000,5.000000,5.950000,0.200000
87,52,0.000000,33.000000,1.216667,4.200000e+01,15.800000,97.900000,4.200000,142000.000000,4.200000,0.500000,74.000000,62.000000,38.000000,70.000000,7.500000,0.770000,3.000000,1.500000,0.500000
88,74,100.000000,16.666667,1.370000,4.570000e+02,11.700000,70.600000,5.700000,138000.000000,4.100000,2.100000,22.000000,33.000000,33.000000,90.000000,9.700000,1.600000,5.000000,5.600000,0.900000
89,61,68.333333,50.000000,1.230000,1.797400e+04,9.500000,90.000000,7.600000,38000.000000,2.200000,1.500000,59.000000,51.000000,993.000000,474.000000,3.900000,2.690000,1.000000,2.000000,1.000000
90,69,100.000000,0.000000,1.410000,1.230000e+02,10.100000,89.500000,2.300000,89000.000000,4.000000,4.300000,31.000000,60.000000,75.000000,177.000000,6.800000,0.700000,3.000000,3.500000,1.000000
91,65,50.000000,20.000000,1.220000,8.700000e+00,14.600000,95.100000,6.700000,142000.000000,4.200000,1.300000,19.000000,33.000000,346.000000,120.000000,7.800000,0.830000,1.333333,3.766667,0.300000
92,79,70.000000,0.000000,1.010000,2.260000e+02,11.500000,95.600000,6.300000,108.000000,4.200000,1.000000,27.000000,31.000000,667.000000,222.000000,6.200000,3.130000,1.000000,8.800000,0.200000
93,69,200.000000,60.000000,1.390000,2.159000e+03,13.100000,90.600000,10400.000000,261000.000000,3.600000,1.900000,42.000000,197.000000,552.000000,335.000000,7.100000,0.680000,5.000000,13.966667,0.600000
94,87,100.000000,50.000000,1.090000,4.800000e+01,12.600000,97.600000,4.900000,169000.000000,4.200000,0.800000,30.000000,31.000000,86.000000,91.000000,6.900000,1.900000,5.000000,2.000000,1.000000
95,78,0.000000,0.000000,1.600000,2.400000e+00,9.500000,85.800000,6900.000000,228000.000000,3.500000,0.600000,11.000000,17.000000,44.000000,124.000000,6.800000,1.600000,1.000000,5.500000,0.500000
96,71,75.000000,0.000000,1.110000,5.000000e+00,9.100000,90.900000,6.360000,307000.000000,2.470000,2.400000,31.000000,29.000000,339.000000,254.000000,5.500000,1.180000,3.000000,6.300000,1.650000
97,58,50.000000,0.000000,1.640000,6.400000e+01,14.100000,103.600000,4.500000,68.000000,2.900000,3.300000,28.000000,43.000000,51.000000,137.000000,6.800000,0.670000,4.000000,4.700000,1.100000
98,73,100.000000,16.666667,1.230000,5.500000e+00,13.100000,89.600000,6.100000,160000.000000,3.200000,0.800000,28.000000,30.000000,90.000000,92.000000,6.300000,0.860000,5.000000,2.000000,0.750000
99,73,100.000000,0.000000,1.670000,8.500000e+00,13.000000,102.300000,24.800000,133000.000000,2.700000,9.500000,262.000000,335.000000,351.000000,66.000000,6.100000,1.200000,5.000000,7.000000,5.500000
100,93,83.333333,0.000000,1.160000,2.785000e+03,12.000000,94.400000,7.900000,78000.000000,2.600000,3.500000,26.000000,34.000000,339.000000,297.000000,5.700000,2.190000,5.000000,6.000000,1.500000

In [13]:
data = Dataset.builderData("hcc_dataset.csv", "?")

,Age,Grams_day,Packs_year,INR,AFP,Hemoglobin,MCV,Leucocytes,Platelets,Albumin,Total_Bil,ALT,AST,GGT,ALP,TP,Creatinine,Nodules,Major_Dim,Dir_Bil,Iron,Sat,Ferritin
0,67,137.0,15.0,1.530,95.00,13.7,106.6,4.900,99.00,3.40,2.10,34.0,41.0,183.0,150.00,7.1,0.70,1.0,3.50,0.50,NaN,NaN,NaN
1,62,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.80,NaN,NaN,NaN,NaN
2,78,50.0,50.0,0.960,5.80,8.9,79.8,8.400,472.00,3.30,0.40,58.0,68.0,202.0,109.00,7.0,2.10,5.0,13.00,0.10,28.0,6.00,16.0
3,77,40.0,30.0,0.950,2440.00,13.4,97.1,9.000,279.00,3.70,0.40,16.0,64.0,94.0,174.00,8.1,1.11,2.0,15.70,0.20,NaN,NaN,NaN
4,76,100.0,30.0,0.940,49.00,14.3,95.1,6.400,199.00,4.10,0.70,147.0,306.0,173.0,109.00,6.9,1.80,1.0,9.00,NaN,59.0,15.00,22.0
5,75,NaN,NaN,1.580,110.00,13.4,91.5,5.400,85.00,3.40,3.50,91.0,122.0,242.0,396.00,5.6,0.90,1.0,10.00,1.40,53.0,22.00,111.0
6,49,0.0,0.0,1.400,138.90,10.4,102.0,3.200,42000.00,2.35,2.72,119.0,183.0,143.0,211.00,7.3,0.80,5.0,2.60,2.19,171.0,126.00,1452.0
7,61,NaN,20.0,1.460,9860.00,10.8,92.0,3.000,58.00,3.10,3.20,79.0,108.0,184.0,300.00,7.1,0.52,2.0,9.00,1.30,42.0,25.00,706.0
8,50,100.0,32.0,3.140,8.80,11.9,107.5,4.900,70.00,1.90,3.30,26.0,59.0,115.0,63.00,6.1,0.59,1.0,6.40,1.20,85.0,73.00,982.0
9,43,100.0,0.0,1.120,1.80,11.8,87.8,5100.000,193000.00,4.20,0.50,71.0,45.0,256.0,303.00,7.1,0.59,1.0,9.30,0.70,NaN,NaN,NaN
10,41,NaN,NaN,1.050,100809.00,13.0,94.2,5.700,196.00,4.40,3.00,90.0,334.0,494.0,236.00,7.6,0.80,5.0,NaN,1.10,NaN,NaN,NaN
11,74,NaN,0.0,1.330,86.00,15.7,96.7,4.000,61.00,3.70,1.30,132.0,168.0,113.0,154.00,NaN,7.60,5.0,1.90,0.30,144.0,41.00,277.0
12,66,NaN,30.0,1.530,60.00,13.3,90.1,5.500,207000.00,4.40,8.50,25.0,36.0,35.0,74.00,8.5,0.73,1.0,5.00,0.80,NaN,NaN,NaN
13,56,0.0,NaN,1.200,6.60,13.7,93.8,4.100,91000.00,4.50,1.00,103.0,96.0,205.0,70.00,8.8,0.88,1.0,22.00,NaN,82.0,24.00,NaN
14,63,NaN,NaN,1.250,29.00,13.5,93.0,6.000,128.00,3.15,10.50,76.0,116.0,165.0,163.00,7.3,1.07,4.0,4.50,4.50,197.0,84.00,302.0
15,41,100.0,0.0,1.610,4.60,10.2,89.6,5.500,161.00,3.10,3.10,24.0,57.0,163.0,176.00,5.0,0.80,2.0,2.60,1.30,25.0,13.00,60.0
16,72,NaN,NaN,2.140,60.00,12.1,99.2,5.000,58.00,2.40,9.80,69.0,63.0,201.0,235.00,6.2,0.96,2.0,2.00,2.90,136.0,95.00,767.0
17,60,100.0,60.0,1.050,9.20,10.3,103.7,5.400,159.00,3.80,0.50,56.0,91.0,459.0,146.00,5.4,1.23,5.0,13.50,3.80,187.0,58.00,443.0
18,64,200.0,78.0,1.130,8.80,14.9,94.8,6.300,137.00,4.30,0.90,16.0,23.0,82.0,180.00,6.5,4.95,1.0,5.40,0.90,144.0,49.00,295.0
19,75,500.0,NaN,1.440,34.00,15.9,103.4,9600.000,101000.00,3.40,3.40,27.0,87.0,260.0,147.00,6.3,0.90,5.0,2.30,1.60,67.0,34.00,774.0
20,71,200.0,60.0,1.290,19.60,11.7,101.0,2600.000,109000.00,3.60,1.70,13.0,35.0,23.0,141.00,7.3,0.68,1.0,2.50,0.70,152.6,NaN,76.9
21,73,80.0,47.0,1.060,3.90,16.4,90.7,7.800,187.00,4.50,1.00,54.0,47.0,52.0,97.00,6.3,0.75,1.0,6.80,0.20,87.0,26.00,84.0
22,66,180.0,0.0,1.270,1975.00,10.8,86.5,9100.000,154000.00,3.10,1.20,68.0,136.0,869.0,562.00,69.0,1.14,5.0,3.80,0.50,112.0,73.00,1001.0
23,64,200.0,60.0,4.820,185.00,10.7,88.1,5.000,194000.00,3.60,3.80,217.0,86.0,879.0,396.00,7.0,0.53,5.0,15.00,1.60,NaN,NaN,NaN
24,84,150.0,NaN,1.740,5532.00,13.1,111.0,3.500,351000.00,2.40,1.30,26.0,67.0,108.0,311.00,5.6,0.95,1.0,10.00,0.70,NaN,NaN,NaN
25,80,100.0,0.0,1.330,13327.00,13.7,94.3,5.200,110.00,3.10,1.60,52.0,107.0,465.0,233.00,8.4,0.79,5.0,NaN,0.70,93.0,31.00,79.0
26,45,50.0,16.0,1.380,NaN,13.6,98.4,4.300,99000.00,3.30,1.30,178.0,325.0,252.0,172.00,8.1,0.83,1.0,5.00,0.70,NaN,NaN,NaN
27,57,NaN,NaN,1.370,5.90,15.5,88.2,4.900,113.00,4.50,3.20,36.0,65.0,34.0,111.00,NaN,NaN,2.0,4.00,1.00,180.0,56.00,NaN
28,61,60.0,67.5,1.300,3255.00,12.2,89.5,4.400,108.00,3.00,1.10,59.0,85.0,419.0,293.00,7.7,0.67,2.0,6.50,0.40,94.0,27.00,70.0
29,20,NaN,2.0,1.210,1.90,9.9,83.4,8.100,556.00,3.20,1.80,150.0,112.0,599.0,974.00,7.7,0.70,5.0,NaN,1.10,22.0,7.00,369.0
30,60,20.0,8.0,1.190,11.00,13.1,87.9,7.800,212.00,3.50,0.70,27.0,26.0,143.0,158.00,8.2,0.71,1.0,16.00,NaN,NaN,NaN,NaN
31,62,120.0,NaN,1.440,1237.00,12.2,94.0,6200.000,93000.00,4.20,1.00,35.0,85.0,191.0,129.00,58.0,1.06,5.0,7.00,NaN,75.0,24.00,239.0
32,67,100.0,NaN,1.320,7.70,15.7,96.1,9.100,268000.00,3.40,0.60,20.0,29.0,49.0,135.00,8.2,0.90,2.0,NaN,NaN,NaN,NaN,NaN
33,77,NaN,NaN,1.240,266.00,13.7,97.7,13000.000,170000.00,4.20,0.50,68.0,85.0,232.0,227.00,16.8,1.72,1.0,5.90,NaN,NaN,NaN,NaN
34,62,NaN,0.0,1.280,5689.00,14.3,99.6,6.800,77.00,3.80,1.70,154.0,102.0,184.0,184.00,6.9,0.89,2.0,3.00,0.77,NaN,NaN,NaN
35,76,0.0,0.0,0.960,14.20,14.8,98.5,4.950,187.00,4.20,0.77,43.0,86.0,89.0,113.00,6.7,0.95,3.0,8.80,0.37,NaN,NaN,NaN
36,73,75.0,0.0,2.000,3.10,13.1,109.3,44.600,60.00,2.30,7.80,38.0,74.0,180.0,127.00,5.6,0.88,5.0,3.10,3.30,98.0,89.00,870.0
37,84,200.0,30.0,1.240,633.00,13.0,96.5,7200.000,143000.00,2.30,1.10,40.0,58.0,322.0,209.00,6.7,1.40,5.0,4.90,0.20,57.0,25.00,134.0
38,70,100.0,0.0,1.090,5.40,14.9,105.0,7.200,230000.00,4.20,1.30,18.0,26.0,174.0,92.00,7.3,0.80,2.0,6.00,0.30,NaN,NaN,NaN
39,59,200.0,0.0,1.420,479.00,11.3,82.2,9500.000,160000.00,3.10,1.40,113.0,143.0,924.0,288.00,7.9,0.98,5.0,17.00,0.60,NaN,NaN,NaN
40,71,0.0,0.0,1.180,19.00,13.9,88.3,6.860,201000.00,4.40,0.80,142.0,117.0,123.0,104.00,8.5,0.74,2.0,3.30,0.30,143.0,50.18,120.0
41,66,0.0,0.0,1.210,2.80,15.7,92.7,15.400,188000.00,4.10,0.70,299.0,553.0,196.0,68.00,6.5,1.30,1.0,5.00,0.30,NaN,NaN,NaN
42,86,NaN,NaN,1.200,185203.00,15.0,85.5,8.800,183.00,3.60,1.00,49.0,117.0,442.0,278.00,7.2,0.86,5.0,15.80,0.30,21.0,9.00,279.0
43,71,75.0,NaN,1.170,5.00,15.1,104.1,4.300,65000.00,3.80,2.50,61.0,56.0,239.0,56.00,7.3,0.70,1.0,2.00,0.20,NaN,NaN,NaN
44,52,0.0,0.0,1.710,237.00,15.6,98.1,4.300,88.00,3.20,2.20,30.0,52.0,72.0,97.00,6.7,0.86,5.0,2.20,0.50,NaN,NaN,NaN
45,60,NaN,0.0,1.180,2.80,16.6,93.8,8300.000,167000.00,4.90,0.90,35.0,29.0,62.0,68.00,8.3,0.72,1.0,2.30,NaN,NaN,NaN,NaN
46,45,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,66,NaN,NaN,1.640,16.00,14.0,102.9,11.500,277000.00,3.10,6.80,140.0,244.0,795.0,595.00,7.2,0.79,1.0,2.30,4.10,63.0,34.00,888.0
48,80,0.0,80.0,1.330,163.00,10.6,96.2,9900.000,280000.00,3.30,1.00,28.0,57.0,236.0,171.00,7.5,1.38,1.0,19.00,NaN,45.0,21.00,802.0
49,58,NaN,40.0,1.490,20.00,15.0,96.7,9.000,78.00,4.60,2.10,40.0,49.0,137.0,109.00,7.6,0.80,1.0,2.00,0.40,184.0,59.00,905.0
50,27,0.0,0.0,0.970,46.00,10.5,78.7,20.900,251.00,2.40,0.30,31.0,185.0,91.0,539.00,5.0,0.38,5.0,20.00,0.30,NaN,NaN,NaN
51,73,100.0,0.0,1.200,41470.00,12.6,91.4,12.000,275000.00,3.11,2.30,55.0,94.0,394.0,350.00,7.3,1.70,5.0,NaN,0.80,84.0,37.00,497.0
52,73,NaN,0.0,1.330,4.70,11.8,80.2,3.700,99.00,4.10,0.70,50.0,47.0,67.0,62.00,7.4,0.77,1.0,2.30,NaN,104.0,37.00,635.0
53,50,NaN,0.0,1.650,7.30,15.3,93.7,3500.000,57000.00,NaN,1.40,111.0,93.0,294.0,130.00,NaN,0.76,2.0,2.00,0.30,184.0,2.26,59.0
54,51,100.0,30.0,1.350,1898.00,12.4,95.1,9.800,216.00,2.70,8.20,164.0,523.0,433.0,397.00,6.7,0.82,1.0,2.10,5.50,56.0,27.00,742.0
55,78,0.0,0.0,1.320,77.00,10.8,88.0,6000.000,174000.00,3.20,0.90,48.0,19.0,171.0,923.00,5.4,1.31,3.0,15.40,NaN,NaN,NaN,NaN
56,81,100.0,10.0,3.560,2.70,7.3,90.8,2.420,159000.00,3.40,0.50,25.0,32.0,80.0,55.00,6.2,0.85,1.0,2.20,NaN,22.0,6.00,48.0
57,65,100.0,NaN,1.240,2.60,10.3,83.0,6.100,1.71,3.90,0.80,11.0,28.0,77.0,120.00,7.0,0.58,1.0,4.70,0.85,32.0,10.00,18.0
58,72,70.0,0.0,1.960,12.00,10.9,102.0,4.100,99.00,1.90,4.20,73.0,85.0,470.0,263.00,7.0,0.99,1.0,8.50,1.90,44.0,20.00,176.0
59,82,0.0,NaN,1.110,NaN,18.7,92.4,6900.000,270000.00,4.00,0.90,35.0,73.0,115.0,103.00,6.8,1.24,1.0,10.00,NaN,NaN,NaN,NaN
60,76,0.0,50.0,1.280,608.00,12.6,100.0,5.400,129.00,4.00,1.70,107.0,99.0,125.0,100.00,7.5,0.90,5.0,3.50,0.50,NaN,NaN,NaN
61,56,100.0,40.0,1.460,41.00,14.6,100.8,5.500,42000.00,3.10,3.70,121.0,165.0,101.0,207.00,6.3,0.69,1.0,3.00,1.90,224.0,95.00,363.0
62,68,NaN,30.0,1.940,NaN,11.5,97.4,5700.000,77000.00,2.70,4.90,34.0,48.0,46.0,178.00,6.1,0.62,1.0,4.60,2.20,NaN,NaN,NaN
63,72,300.0,NaN,1.570,2.00,12.6,96.6,2.900,76000.00,3.50,2.40,33.0,40.0,110.0,166.00,NaN,0.77,1.0,2.00,0.50,NaN,NaN,NaN
64,66,0.0,0.0,1.290,7.00,12.1,95.1,3.800,77000.00,3.80,1.40,37.0,38.0,194.0,161.00,6.7,0.71,1.0,10.00,0.50,0.0,0.00,0.0
65,40,0.0,0.0,1.170,3.10,15.1,86.0,8.900,275000.00,2.80,1.30,74.0,50.0,23.0,104.00,5.4,0.60,5.0,7.80,0.20,46.0,18.00,NaN
66,68,60.0,NaN,1.340,13.00,15.6,93.0,4.900,91000.00,4.54,1.40,54.0,52.0,275.0,113.00,7.8,0.55,2.0,6.20,0.30,94.0,33.00,393.0
67,63,100.0,0.0,2.070,1.70,9.5,99.2,3300.000,79000.00,2.10,1.60,56.0,82.0,134.0,113.00,37.0,0.40,1.0,2.70,0.20,94.0,37.00,48.0
68,72,100.0,0.0,1.300,249.00,12.7,100.3,5.500,114.00,3.10,3.90,21.0,42.0,40.0,108.00,5.8,0.90,5.0,8.00,1.20,37.0,17.00,419.0
69,88,80.0,0.0,1.270,66.00,10.9,97.3,8.900,270.00,2.70,2.10,145.0,84.0,179.0,260.00,5.9,NaN,5.0,3.00,1.30,15.0,17.00,639.0
70,23,0.0,0.0,1.170,358.00,12.7,74.0,2.200,51.00,2.90,2.80,53.0,41.0,54.0,94.00,4.9,0.20,2.0,5.40,0.80,50.0,16.00,20.0
71,59,75.0,44.0,1.010,1810346.00,13.0,102.1,8300.000,433000.00,3.40,1.90,138.0,86.0,1575.0,417.00,6.5,0.64,5.0,15.00,1.10,NaN,NaN,NaN
72,82,50.0,48.0,1.530,33502.00,14.4,101.1,11.600,109.00,3.10,2.30,27.0,80.0,177.0,1.28,6.7,1.50,5.0,4.00,0.80,26.0,15.00,227.0
73,67,NaN,0.0,0.940,20.00,13.0,92.0,6.900,222000.00,3.70,0.60,162.0,354.0,1390.0,684.00,7.1,0.81,5.0,NaN,NaN,NaN,NaN,NaN
74,61,NaN,15.0,1.150,2.50,14.9,92.3,6.000,159000.00,3.80,1.00,28.0,38.0,74.0,101.00,7.4,1.10,5.0,7.50,0.30,61.0,NaN,255.0
75,61,100.0,NaN,1.920,2269.00,12.1,119.0,5.100,80000.00,NaN,9.60,204.0,357.0,199.0,174.00,NaN,0.99,1.0,7.60,4.60,178.0,90.00,960.0
76,67,NaN,NaN,3.160,4181.00,9.1,103.6,5.100,128000.00,3.00,2.20,57.0,91.0,115.0,165.00,7.7,0.83,1.0,4.50,1.20,72.0,29.50,355.0
77,78,80.0,NaN,1.450,5.10,14.4,100.2,7.100,77000.00,4.10,0.90,43.0,63.0,540.0,114.00,7.0,1.09,5.0,NaN,NaN,NaN,NaN,NaN
78,52,80.0,NaN,1.340,345.00,9.8,81.8,13.600,561.00,2.60,0.50,43.0,43.0,23.0,88.00,5.6,NaN,5.0,4.70,0.50,19.0,8.00,141.0
79,51,100.0,34.5,2.080,2.90,10.4,91.1,5.800,91000.00,2.40,16.00,123.0,145.0,109.0,190.00,5.9,0.90,0.0,NaN,9.60,NaN,NaN,NaN
80,74,NaN,NaN,1.320,2.50,12.6,83.7,9.800,102000.00,3.30,1.20,29.0,43.0,196.0,204.00,7.3,1.10,5.0,NaN,0.50,NaN,NaN,NaN
81,56,100.0,NaN,1.630,5.04,15.8,99.0,5.800,75000.00,3.50,4.60,93.0,85.0,193.0,165.00,6.6,0.70,1.0,6.00,1.70,200.0,87.00,316.0
82,64,100.0,0.0,1.710,3.70,14.8,104.3,5.800,56000.00,2.70,2.60,74.0,157.0,311.0,280.00,8.0,0.80,2.0,3.00,1.40,NaN,1.52,859.0
83,83,100.0,NaN,1.480,2.60,12.7,106.0,3.800,80.00,2.90,3.40,34.0,53.0,156.0,207.00,7.2,NaN,2.0,4.10,1.40,105.0,69.00,221.0
84,57,0.0,NaN,1.100,2.90,16.4,94.8,4.600,94000.00,4.10,1.10,104.0,74.0,88.0,85.00,7.9,1.05,1.0,5.50,0.30,NaN,NaN,NaN
85,58,NaN,10.0,1.470,20.00,13.9,100.8,4.000,112000.00,3.00,2.90,50.0,92.0,124.0,244.00,6.3,0.80,2.0,6.80,0.70,181.0,99.00,108.0
86,71,NaN,NaN,1.080,2.79,12.6,83.9,7100.000,284000.00,NaN,NaN,28.0,46.0,70.0,213.00,NaN,0.48,5.0,NaN,NaN,26.0,8.00,NaN
87,52,0.0,33.0,NaN,42.00,15.8,97.9,4.200,142000.00,4.20,0.50,74.0,62.0,38.0,70.00,7.5,0.77,3.0,1.50,NaN,120.0,35.00,30.0
88,74,100.0,NaN,1.370,457.00,11.7,70.6,5.700,138000.00,4.10,2.10,22.0,33.0,33.0,90.00,9.7,1.60,5.0,5.60,0.90,13.0,3.00,28.0
89,61,NaN,50.0,1.230,NaN,9.5,90.0,7.600,38000.00,2.20,1.50,59.0,51.0,993.0,474.00,3.9,2.69,1.0,2.00,1.00,NaN,NaN,NaN
90,69,100.0,0.0,1.410,123.00,10.1,89.5,2.300,89000.00,4.00,4.30,31.0,60.0,75.0,177.00,6.8,0.70,3.0,3.50,1.00,37.0,11.00,173.0
91,65,NaN,NaN,1.220,8.70,14.6,95.1,6.700,142000.00,4.20,1.30,19.0,33.0,346.0,120.00,7.8,0.83,NaN,NaN,0.30,184.0,65.00,423.0
92,79,70.0,0.0,1.010,226.00,11.5,95.6,6.300,108.00,4.20,1.00,27.0,31.0,667.0,222.00,6.2,3.13,1.0,8.80,0.20,NaN,NaN,NaN
93,69,200.0,60.0,1.390,2159.00,13.1,90.6,10400.000,261000.00,3.60,1.90,42.0,197.0,552.0,335.00,7.1,0.68,5.0,NaN,0.60,NaN,NaN,NaN
94,87,100.0,50.0,1.090,48.00,12.6,97.6,4.900,169000.00,4.20,0.80,30.0,31.0,86.0,91.00,6.9,1.90,5.0,2.00,NaN,53.0,21.00,278.0
95,78,0.0,0.0,1.600,2.40,9.5,85.8,6900.000,228000.00,3.50,0.60,11.0,17.0,44.0,124.00,6.8,1.60,1.0,5.50,NaN,15.0,7.00,810.0
96,71,NaN,0.0,1.110,5.00,9.1,90.9,6.360,307000.00,2.47,NaN,31.0,29.0,339.0,254.00,5.5,1.18,3.0,6.30,NaN,NaN,NaN,NaN
97,58,NaN,NaN,1.640,64.00,14.1,103.6,4.500,68.00,2.90,3.30,28.0,43.0,51.0,137.00,6.8,0.67,4.0,4.70,1.10,NaN,NaN,NaN
98,73,NaN,NaN,1.230,5.50,13.1,89.6,6.100,160000.00,3.20,0.80,28.0,30.0,90.0,92.00,6.3,0.86,5.0,NaN,NaN,93.0,25.00,29.0
99,73,NaN,0.0,1.670,8.50,13.0,102.3,24.800,133000.00,2.70,9.50,262.0,335.0,351.0,66.00,6.1,1.20,5.0,7.00,5.50,NaN,NaN,NaN
100,93,NaN,0.0,1.160,2785.00,12.0,94.4,7.900,78000.00,2.60,3.50,26.0,34.0,339.0,297.00,5.7,2.19,5.0,NaN,1.50,55.0,33.00,256.0
101,52,0.0,NaN,1.040,6574.00,13.5,98.0,4800.000,77000.00,3.50,28.90,56.0,192.0,464.0,262.00,6.9,1.20,5.0,4.00,19.50,121.0,27.00,749.0
102,64,70.0,NaN,1.550,5.70,13.9,99.7,5200.000,124000.00,2.10,0.80,37.0,75.0,203.0,110.00,5.0,0.56,3.0,2.40,NaN,92.0,56.00,489.0
103,63,0.0,NaN,1.930,NaN,13.5,93.3,8190.000,406000.00,2.90,40.50,139.0,266.0,403.0,670.00,6.3,4.82,5.0,NaN,29.30,NaN,NaN,NaN
104,64,0.0,50.0,1.170,39.00,12.6,93.8,4900.000,144000.00,3.80,1.00,42.0,74.0,277.0,312.00,78.0,1.01,1.0,15.00,NaN,87.0,25.00,81.0
105,67,NaN,0.0,1.480,2.50,14.3,101.5,5.000,120.00,2.20,1.20,34.0,71.0,222.0,97.00,5.2,2.82,3.0,2.40,0.30,92.0,56.00,48.9
106,50,80.0,1.0,1.180,32.00,14.0,90.1,5.200,121000.00,4.20,0.40,420.0,226.0,147.0,174.00,8.6,0.90,5.0,3.00,NaN,26.4,54.00,2230.0
107,79,75.0,0.0,1.320,7.60,5.0,69.5,3800.000,96000.00,3.70,0.50,17.0,69.0,76.0,86.00,6.3,2.68,1.0,10.00,NaN,9.0,3.00,490.0
108,85,100.0,0.0,1.250,173.00,11.3,103.9,6200.000,176000.00,2.40,1.70,63.0,114.0,80.0,163.00,6.1,0.67,5.0,20.00,0.50,131.0,78.00,1316.0
109,62,NaN,NaN,1.540,2.30,12.1,89.7,4.500,97000.00,2.70,1.40,19.0,27.0,72.0,120.00,4.3,0.61,5.0,4.00,0.70,NaN,NaN,NaN
110,74,200.0,30.0,1.260,114.00,14.9,104.5,4.300,90000.00,3.20,4.80,106.0,154.0,148.0,166.00,7.2,0.48,5.0,12.60,1.80,161.0,96.00,297.0
111,56,90.0,NaN,1.870,173.00,11.1,105.5,6.100,51000.00,3.10,32.30,110.0,206.0,127.0,188.00,5.4,1.29,5.0,NaN,22.10,NaN,NaN,NaN
112,74,100.0,NaN,1.360,18.00,15.3,90.9,4.900,81000.00,4.20,1.70,35.0,49.0,97.0,109.00,7.3,1.02,1.0,3.50,0.30,NaN,NaN,NaN
113,62,0.0,7.5,1.450,42.00,16.2,99.1,5.001,77000.00,4.10,1.30,42.0,118.0,279.0,158.00,7.7,0.88,2.0,7.40,0.30,NaN,NaN,NaN
114,60,100.0,NaN,1.870,28274.00,10.3,94.7,11.100,109000.00,2.40,5.70,25.0,111.0,55.0,128.00,7.0,1.30,1.0,1.50,1.90,51.0,18.00,56.0
115,55,100.0,43.0,1.230,736.00,14.0,88.2,4.680,286000.00,4.70,0.80,48.0,113.0,649.0,629.00,8.4,0.71,5.0,9.10,0.30,NaN,NaN,NaN
116,57,96.0,60.0,1.170,1009.00,13.8,93.2,3100.000,137000.00,3.00,0.70,25.0,55.0,343.0,235.00,NaN,0.79,2.0,20.00,NaN,NaN,NaN,NaN
117,63,120.0,NaN,2.420,22475.00,12.0,111.4,9.900,70000.00,3.28,19.00,134.0,178.0,54.0,146.00,8.0,3.23,1.0,NaN,9.70,106.0,67.00,2165.0
118,63,NaN,0.0,1.280,5.20,14.6,96.1,6.100,194000.00,4.20,7.90,97.0,69.0,816.0,79.00,7.7,1.02,1.0,3.00,NaN,NaN,NaN,NaN
119,79,180.0,23.0,1.460,5.20,14.9,103.8,4500.000,53000.00,3.20,1.40,62.0,87.0,263.0,239.00,8.1,0.72,1.0,1.50,1.00,NaN,NaN,NaN
120,63,0.0,0.0,1.140,14177.00,10.2,96.1,6000.000,109000.00,2.60,4.90,70.0,113.0,833.0,980.00,7.5,0.78,5.0,9.00,2.80,NaN,NaN,NaN
121,59,100.0,0.0,1.940,3.10,10.8,102.8,5300.000,97000.00,3.60,1.10,119.0,125.0,663.0,433.00,6.5,0.87,2.0,3.20,0.40,52.5,37.00,856.0
122,51,75.0,52.5,1.560,50655.00,9.8,85.6,3900.000,132000.00,2.60,2.60,123.0,219.0,503.0,363.00,7.3,0.55,1.0,4.00,1.50,40.0,12.00,57.0
123,74,0.0,0.0,1.110,1.20,15.1,83.8,5.200,178000.00,4.70,0.50,35.0,17.0,45.3,151.00,6.4,1.50,1.0,8.30,NaN,88.0,27.00,90.0
124,62,NaN,NaN,1.080,657.00,11.8,89.2,9400.000,211000.00,3.20,0.80,43.0,101.0,646.0,466.00,7.3,0.70,1.0,8.30,NaN,NaN,NaN,579.0
125,76,100.0,NaN,1.200,421500.00,14.3,89.5,9.800,309000.00,3.10,1.50,20.0,44.0,291.0,217.00,6.3,0.70,1.0,20.00,0.50,52.0,17.00,832.0
126,73,0.0,NaN,1.200,472.00,15.6,88.4,5.500,83000.00,4.00,2.40,117.0,128.0,249.0,117.00,7.2,0.69,1.0,13.00,0.70,NaN,NaN,NaN
127,76,NaN,0.0,1.660,77.00,12.3,104.2,2900.000,60000.00,3.20,2.80,54.0,38.0,311.0,182.00,6.2,0.77,2.0,4.30,1.00,93.0,47.00,307.0
128,72,0.0,510.0,1.130,2.10,12.6,95.1,8.700,254000.00,3.68,0.70,26.0,38.0,161.0,127.00,6.9,1.11,2.0,4.30,NaN,28.0,10.00,308.0
129,77,75.0,0.0,1.070,2.00,11.6,83.5,9.000,318000.00,3.89,0.90,23.0,48.0,319.0,171.00,7.1,0.66,2.0,5.80,NaN,NaN,NaN,NaN
130,75,0.0,0.0,1.220,4.20,14.9,87.4,15.400,179000.00,3.50,0.60,31.0,61.0,196.0,150.00,5.4,0.70,5.0,17.50,0.30,NaN,NaN,NaN
131,55,100.0,NaN,2.500,7.50,11.3,119.6,13.100,135000.00,3.20,8.60,62.0,94.0,82.0,147.00,6.5,1.00,5.0,2.60,3.80,NaN,NaN,NaN
132,72,0.0,0.0,1.210,152.00,10.9,99.6,7.300,93000.00,3.20,1.30,82.0,80.0,427.0,106.00,7.1,6.10,2.0,9.00,0.70,NaN,NaN,NaN
133,82,0.0,0.0,1.090,811.00,11.4,89.3,9.100,318000.00,3.40,0.80,77.0,102.0,739.0,587.00,7.2,2.14,5.0,16.00,NaN,14.0,5.00,149.0
134,46,0.0,0.0,1.420,4.70,14.2,90.3,6690.000,268000.00,3.10,0.32,37.0,44.0,80.0,517.00,5.5,0.70,1.0,13.00,0.12,NaN,NaN,NaN
135,71,0.0,0.0,1.240,2.60,13.3,96.4,7.800,280000.00,4.10,0.60,70.0,52.0,141.0,123.00,6.8,0.82,5.0,8.30,NaN,NaN,NaN,NaN
136,56,0.0,40.0,1.250,2089.00,15.4,91.6,10.900,175000.00,4.40,1.30,45.0,32.0,717.0,295.00,7.4,1.10,5.0,6.00,0.60,NaN,NaN,NaN
137,78,0.0,0.0,1.030,18.00,13.2,89.5,2.600,136000.00,4.30,0.80,18.0,29.0,82.0,141.00,7.2,0.85,1.0,9.50,NaN,91.0,31.00,80.0
138,55,0.0,NaN,1.190,4.90,13.6,97.3,5400.000,133000.00,4.50,0.90,54.0,63.0,487.0,89.00,7.8,0.78,2.0,3.32,NaN,78.0,30.00,220.0
139,76,NaN,12.0,0.940,240.00,14.7,102.3,9.900,267000.00,3.60,0.50,64.0,132.0,356.0,192.00,7.4,0.90,3.0,2.00,0.40,NaN,NaN,NaN
140,43,0.0,0.0,1.250,180.00,12.2,87.6,7.200,130.00,3.50,0.50,79.0,58.0,229.0,302.00,7.0,0.60,5.0,9.00,NaN,NaN,NaN,206.0
141,71,0.0,NaN,1.470,15.00,13.3,89.7,5.700,154000.00,3.20,1.00,NaN,87.0,120.0,108.00,102.0,0.68,3.0,2.00,NaN,NaN,NaN,NaN
142,67,70.0,0.0,1.020,24.00,16.0,98.8,6.600,96000.00,4.10,1.40,207.0,158.0,116.0,84.00,7.2,0.90,1.0,2.20,0.30,NaN,NaN,NaN
143,67,NaN,40.0,1.798,9.40,11.2,102.4,4.100,60000.00,3.40,3.70,43.0,63.0,175.0,106.00,7.6,0.52,1.0,2.10,1.10,94.0,39.00,344.0
144,51,NaN,37.0,1.260,7.00,14.9,106.3,6.400,122.00,3.00,1.50,195.0,401.0,272.0,93.00,6.4,1.00,3.0,2.90,0.40,124.0,51.00,642.0
145,80,NaN,NaN,1.000,4.80,9.2,94.0,6.200,157000.00,3.88,0.76,42.0,51.0,983.0,141.00,NaN,1.10,1.0,15.00,0.33,NaN,NaN,NaN
146,79,100.0,15.0,1.680,92421.00,14.3,72.2,13.300,459000.00,3.20,1.60,24.0,76.0,570.0,472.00,5.9,2.02,1.0,NaN,0.60,29.0,4.00,14.0
147,75,NaN,NaN,1.710,5.20,11.1,106.9,2100.000,52000.00,3.30,2.60,15.0,47.0,94.0,117.00,7.1,0.79,1.0,3.50,1.00,NaN,NaN,NaN
148,81,0.0,0.0,1.180,16.00,13.3,94.3,4800.000,96000.00,3.80,1.20,26.0,35.0,75.0,105.00,7.6,0.53,1.0,2.40,0.30,NaN,NaN,NaN
149,25,0.0,0.0,NaN,1.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,6.60,NaN,NaN,NaN,NaN
150,36,0.0,0.0,1.120,3204.00,16.1,92.0,10.500,182.00,4.30,0.70,46.0,31.0,92.0,79.00,7.3,1.00,1.0,NaN,0.20,NaN,NaN,NaN
151,69,NaN,NaN,1.200,10.00,13.5,104.9,13.500,194.00,4.00,1.00,31.0,79.0,126.0,85.00,7.6,0.80,1.0,7.00,0.40,NaN,NaN,NaN
152,47,250.0,18.0,1.390,695.00,11.1,93.9,5.400,88000.00,2.70,1.00,31.0,73.0,38.0,44.00,7.0,0.96,5.0,3.50,NaN,NaN,NaN,NaN
153,87,NaN,0.0,1.200,33.00,9.7,91.6,10.100,277.00,3.80,2.40,60.0,54.0,468.0,338.00,7.0,1.13,1.0,15.00,1.30,NaN,NaN,NaN
154,36,0.0,0.0,1.520,615.00,11.7,99.7,5.600,70000.00,2.82,3.00,66.0,50.0,120.0,318.00,6.4,0.64,5.0,1.90,1.00,NaN,NaN,NaN
155,64,75.0,25.0,1.630,1671.00,12.8,101.6,4.400,172000.00,3.44,5.80,38.0,95.0,92.0,139.00,7.6,0.90,3.0,9.00,2.90,111.0,94.00,1600.0
156,49,NaN,0.0,1.240,975.00,15.3,103.0,11.500,124000.00,3.50,1.20,62.0,85.0,561.0,266.00,7.5,0.77,1.0,2.30,0.60,180.0,70.00,1176.0
157,62,NaN,20.0,1.410,1.70,14.7,97.2,6900.000,72000.00,3.50,1.30,31.0,24.0,67.0,97.00,7.3,0.76,1.0,3.50,0.30,NaN,NaN,NaN
158,71,0.0,NaN,1.160,1713.00,8.2,94.2,6.000,209000.00,3.60,0.30,62.0,59.0,450.0,263.00,6.8,1.49,1.0,7.50,NaN,NaN,NaN,NaN
159,64,100.0,0.0,1.520,4.90,7.9,111.2,4.100,67000.00,2.43,1.90,40.0,71.0,69.0,73.00,4.8,0.77,5.0,3.20,0.70,40.0,18.00,283.0

# LOGISTIC REGRESSION