In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('hcc_dataset.csv')

In [4]:
df

,Gender,Symptoms,Alcohol,HBsAg,HBeAg,HBcAb,HCVAb,Cirrhosis,Endemic,Smoking,...,ALP,TP,Creatinine,Nodules,Major_Dim,Dir_Bil,Iron,Sat,Ferritin,Class
0,Male,No,Yes,No,No,No,No,Yes,No,Yes,...,150,7.1,0.7,1,3.5,0.5,?,?,?,Lives
1,Female,?,No,No,No,No,Yes,Yes,?,?,...,?,?,?,1,1.8,?,?,?,?,Lives
2,Male,No,Yes,Yes,No,Yes,No,Yes,No,Yes,...,109,7,2.1,5,13,0.1,28,6,16,Lives
3,Male,Yes,Yes,No,No,No,No,Yes,No,Yes,...,174,8.1,1.11,2,15.7,0.2,?,?,?,Dies
4,Male,Yes,Yes,Yes,No,Yes,No,Yes,No,Yes,...,109,6.9,1.8,1,9,?,59,15,22,Lives
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,Female,No,Yes,?,?,?,Yes,Yes,No,Yes,...,109,7.6,0.7,5,3,?,?,?,?,Lives
161,Female,Yes,No,?,?,?,?,Yes,No,No,...,280,6.7,0.7,1,2.2,2.3,?,?,?,Dies
162,Male,No,Yes,No,No,No,No,Yes,No,Yes,...,181,7.5,1.46,5,18.6,?,?,?,?,Lives
163,Male,No,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,...,170,8.4,0.74,5,18,?,?,?,?,Dies
164,Male,Yes,Yes,No,No,No,Yes,Yes,No,Yes,...,462,6.6,3.95,5,8.5,19.8,?,?,?,Dies

In [8]:
df.columns

Index(['Gender', 'Symptoms', 'Alcohol', 'HBsAg', 'HBeAg', 'HBcAb', 'HCVAb',
       'Cirrhosis', 'Endemic', 'Smoking', 'Diabetes', 'Obesity', 'Hemochro',
       'AHT', 'CRI', 'HIV', 'NASH', 'Varices', 'Spleno', 'PHT', 'PVT',
       'Metastasis', 'Hallmark', 'Age', 'Grams_day', 'Packs_year', 'PS',
       'Encephalopathy', 'Ascites', 'INR', 'AFP', 'Hemoglobin', 'MCV',
       'Leucocytes', 'Platelets', ' Albumin', 'Total_Bil', 'ALT', 'AST', 'GGT',
       'ALP', 'TP', 'Creatinine', 'Nodules', 'Major_Dim', 'Dir_Bil', 'Iron',
       'Sat', 'Ferritin', 'Class'],
      dtype='object')

In [9]:
df.shape

(165, 50)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 50 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          165 non-null    object
 1   Symptoms        165 non-null    object
 2   Alcohol         165 non-null    object
 3   HBsAg           165 non-null    object
 4   HBeAg           165 non-null    object
 5   HBcAb           165 non-null    object
 6   HCVAb           165 non-null    object
 7   Cirrhosis       165 non-null    object
 8   Endemic         165 non-null    object
 9   Smoking         165 non-null    object
 10  Diabetes        165 non-null    object
 11  Obesity         165 non-null    object
 12  Hemochro        165 non-null    object
 13  AHT             165 non-null    object
 14  CRI             165 non-null    object
 15  HIV             165 non-null    object
 16  NASH            165 non-null    object
 17  Varices         165 non-null    object
 18  Spleno          165 non-null    object
 19  PHT             165 non-null    object
 20  PVT             165 non-null    object
 21  Metastasis      165 non-null    object
 22  Hallmark        165 non-null    object
 23  Age             165 non-null    int64
 24  Grams_day       165 non-null    object
 25  Packs_year      165 non-null    object
 26  PS              165 non-null    object
 27  Encephalopathy  165 non-null    object
 28  Ascites         165 non-null    object
 29  INR             165 non-null    object
 30  AFP             165 non-null    object
 31  Hemoglobin      165 non-null    object
 32  MCV             165 non-null    object
 33  Leucocytes      165 non-null    object
 34  Platelets       165 non-null    object
 35   Albumin        165 non-null    object
 36  Total_Bil       165 non-null    object
 37  ALT             165 non-null    object
 38  AST             165 non-null    object
 39  GGT             165 non-null    object
 40  ALP             165 non-null    object
 41  TP              165 non-null    object
 42  Creatinine      165 non-null    object
 43  Nodules         165 non-null    object
 44  Major_Dim       165 non-null    object
 45  Dir_Bil         165 non-null    object
 46  Iron            165 non-null    object
 47  Sat             165 non-null    object
 48  Ferritin        165 non-null    object
 49  Class           165 non-null    object
dtypes: int64(1), object(49)
memory usage: 64.6+ KB